//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSLayerGroup.h"

@protocol _MSArtboardGroup <MSLayerGroup>
@property(readonly, nonatomic) id <MSRulerData> verticalRulerDataGeneric;
@property(readonly, nonatomic) id <MSLayoutGrid> layoutGeneric;
@property(readonly, nonatomic) id <MSRulerData> horizontalRulerDataGeneric;
@property(readonly, nonatomic) id <MSSimpleGrid> gridGeneric;
@property(readonly, nonatomic) id <MSColor> backgroundColorGeneric;
@property(readonly, nonatomic) BOOL includeInCloudUpload;
@property(readonly, nonatomic) BOOL includeBackgroundColorInExport;
@property(readonly, nonatomic) BOOL hasBackgroundColor;
@end

