//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchModel/MSGroupLayout.h>

@interface _MSInferredGroupLayout : MSGroupLayout
{
    unsigned long long _axis;
    unsigned long long _layoutAnchor;
    double _maxSize;
    double _minSize;
}

+ (BOOL)allowsFaulting;
+ (Class)immutableClass;
- (void)setRaw_minSize:(double)arg1;
- (void)setRaw_maxSize:(double)arg1;
- (void)setRaw_layoutAnchor:(unsigned long long)arg1;
- (void)setRaw_axis:(unsigned long long)arg1;
- (id)collaborationPatchableObjectWithID:(id)arg1;
- (void)pluginDiffCompareChildrenAgainst:(id)arg1 treeComparison:(id)arg2;
- (void)syncPropertiesFromObject:(id)arg1;
- (BOOL)propertiesAreEqual:(id)arg1 forPurpose:(unsigned long long)arg2;
- (void)copyPropertiesToObject:(id)arg1 options:(unsigned long long)arg2;
- (void)setAsParentOnChildren;
- (void)initializeUnsetObjectPropertiesWithDefaults;
- (BOOL)hasDefaultValues;
- (void)performInitEmptyObject;
@property(nonatomic) double minSize; // @synthesize minSize=_minSize;
@property(nonatomic) double maxSize; // @synthesize maxSize=_maxSize;
@property(nonatomic) unsigned long long layoutAnchor; // @synthesize layoutAnchor=_layoutAnchor;
@property(nonatomic) unsigned long long axis; // @synthesize axis=_axis;
- (void)performInitWithImmutableModelObject:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;

@end

