//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStylePart.h"

@class MSColor, MSGradient, MSGraphicsContextSettings;

@interface _MSStyleBasicFill : MSStylePart
{
    unsigned long long _fillType;
    MSColor *_color;
    MSGraphicsContextSettings *_contextSettings;
    MSGradient *_gradient;
}

+ (BOOL)allowsFaulting;
+ (Class)immutableClass;
- (void).cxx_destruct;
- (BOOL)propertiesAreEqual:(id)arg1;
- (void)copyPropertiesToObject:(id)arg1 options:(unsigned long long)arg2;
- (void)setAsParentOnChildren;
- (void)initializeUnsetObjectPropertiesWithDefaults;
- (BOOL)hasDefaultValues;
- (void)performInitEmptyObject;
- (void)setPrimitiveGradient:(id)arg1;
- (id)primitiveGradient;
- (void)setPrimitiveContextSettings:(id)arg1;
- (id)primitiveContextSettings;
- (void)setPrimitiveColor:(id)arg1;
- (id)primitiveColor;
- (void)setPrimitiveFillType:(unsigned long long)arg1;
- (unsigned long long)primitiveFillType;
@property(retain, nonatomic) MSGradient *gradient; // @synthesize gradient=_gradient;
- (id)gradientGeneric;
@property(retain, nonatomic) MSGraphicsContextSettings *contextSettings; // @synthesize contextSettings=_contextSettings;
- (id)contextSettingsGeneric;
@property(retain, nonatomic) MSColor *color; // @synthesize color=_color;
- (id)colorGeneric;
@property(nonatomic) unsigned long long fillType; // @synthesize fillType=_fillType;
- (void)performInitWithImmutableModelObject:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;

@end

