//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSStyledLayer.h"

@class NSArray, NSMutableArray, NSString;

@interface _MSSymbolInstance : MSStyledLayer
{
    double _horizontalSpacing;
    double _masterInfluenceEdgeMaxXPadding;
    double _masterInfluenceEdgeMaxYPadding;
    double _masterInfluenceEdgeMinXPadding;
    double _masterInfluenceEdgeMinYPadding;
    double _scale;
    NSString *_symbolID;
    double _verticalSpacing;
    NSMutableArray *_overrideValues;
}

+ (BOOL)allowsFaulting;
+ (Class)immutableClass;
- (void).cxx_destruct;
- (void)syncPropertiesFromObject:(id)arg1;
- (BOOL)propertiesAreEqual:(id)arg1;
- (void)copyPropertiesToObject:(id)arg1 options:(unsigned long long)arg2;
- (void)setAsParentOnChildren;
- (void)moveOverrideValueIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)removeAllOverrideValues;
- (void)removeOverrideValuesAtIndexes:(id)arg1;
- (void)removeOverrideValueAtIndex:(unsigned long long)arg1;
- (void)removeOverrideValue:(id)arg1;
- (void)insertOverrideValues:(id)arg1 afterOverrideValue:(id)arg2;
- (void)insertOverrideValue:(id)arg1 afterOverrideValue:(id)arg2;
- (void)insertOverrideValues:(id)arg1 beforeOverrideValue:(id)arg2;
- (void)insertOverrideValue:(id)arg1 beforeOverrideValue:(id)arg2;
- (void)insertOverrideValue:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addOverrideValues:(id)arg1;
- (void)addOverrideValue:(id)arg1;
- (void)initializeUnsetObjectPropertiesWithDefaults;
- (BOOL)hasDefaultValues;
- (void)performInitEmptyObject;
@property(retain, nonatomic) NSArray *overrideValues; // @synthesize overrideValues=_overrideValues;
@property(nonatomic) double verticalSpacing; // @synthesize verticalSpacing=_verticalSpacing;
@property(retain, nonatomic) NSString *symbolID; // @synthesize symbolID=_symbolID;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) double masterInfluenceEdgeMinYPadding; // @synthesize masterInfluenceEdgeMinYPadding=_masterInfluenceEdgeMinYPadding;
@property(nonatomic) double masterInfluenceEdgeMinXPadding; // @synthesize masterInfluenceEdgeMinXPadding=_masterInfluenceEdgeMinXPadding;
@property(nonatomic) double masterInfluenceEdgeMaxYPadding; // @synthesize masterInfluenceEdgeMaxYPadding=_masterInfluenceEdgeMaxYPadding;
@property(nonatomic) double masterInfluenceEdgeMaxXPadding; // @synthesize masterInfluenceEdgeMaxXPadding=_masterInfluenceEdgeMaxXPadding;
@property(nonatomic) double horizontalSpacing; // @synthesize horizontalSpacing=_horizontalSpacing;
- (void)performInitWithImmutableModelObject:(id)arg1;
- (void)enumerateChildProperties:(CDUnknownBlockType)arg1;
- (void)enumerateProperties:(CDUnknownBlockType)arg1;

@end

