//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSProgressIndicator, NSTextField;

@interface _TtC6Sketch38MSCloudDocumentDownloadsViewController : NSViewController
{
    // Error parsing type: , name: progressBar
    // Error parsing type: , name: explanationLabel
    // Error parsing type: , name: downloadsProgress
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic, retain) NSTextField *explanationLabel; // @synthesize explanationLabel;
@property(nonatomic, retain) NSProgressIndicator *progressBar; // @synthesize progressBar;

@end

