//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC13SharedEditing17PatchDownloadTask : _TtCs12_SwiftObject
{
    // Error parsing type: , name: isCancelled
    // Error parsing type: , name: download
    // Error parsing type: , name: remotePatch
    // Error parsing type: , name: delegate
    // Error parsing type: , name: strongDelegate
    // Error parsing type: , name: completionBlock
}

@end

