//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_TtC6Sketch23ComponentListController.h"

#import "NSMenuDelegate-Protocol.h"

@interface _TtC6Sketch23ComponentListController (Sketch2) <NSMenuDelegate>
- (void)reveal:(id)arg1;
- (void)rename:(id)arg1;
@end

