//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchModel/MSBezierFillet.h>

@interface _TtC11SketchModel30MSDivideAndConquerBezierFillet : MSBezierFillet
{
}

+ (id)bezierFilletWithSegment1:(id)arg1 segment2:(id)arg2 filletRadius:(double)arg3;
- (id)init;
- (id)initWithSegment1:(id)arg1 segment2:(id)arg2 segment1Offset:(double)arg3 segment2Offset:(double)arg4 arcEndPoint1:(struct CGPoint)arg5 arcEndPoint2:(struct CGPoint)arg6 arcCenter:(struct CGPoint)arg7 arcRadius:(double)arg8;

@end

