//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC13SharedEditing16PresenceObserverP33_A4EE37373A358E8B210F33C07586A2EF17DelegateContainer : _TtCs12_SwiftObject
{
    // Error parsing type: , name: delegate
}

@end

