//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Sketch22ComponentInspectorItem.h"

@class MSColor, MSInspectorPushButton, NSMenu, NSTextField;

@interface _TtC6Sketch28MSColorVariableInspectorItem : _TtC6Sketch22ComponentInspectorItem
{
    // Error parsing type: , name: selectedColor
    // Error parsing type: , name: renameTextField
    // Error parsing type: , name: createColorButton
    // Error parsing type: , name: updateColorButton
    // Error parsing type: , name: detachColorButton
    // Error parsing type: , name: moreActionsButton
    // Error parsing type: , name: moreActionsMenu
    // Error parsing type: , name: renameCompletionHandler
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (void)commitColorName:(id)arg1;
- (void)showMoreActionsMenu:(id)arg1;
@property(nonatomic) __weak NSMenu *moreActionsMenu; // @synthesize moreActionsMenu;
@property(nonatomic) __weak MSInspectorPushButton *moreActionsButton; // @synthesize moreActionsButton;
@property(nonatomic) __weak MSInspectorPushButton *detachColorButton; // @synthesize detachColorButton;
@property(nonatomic) __weak MSInspectorPushButton *updateColorButton; // @synthesize updateColorButton;
@property(nonatomic) __weak MSInspectorPushButton *createColorButton; // @synthesize createColorButton;
@property(nonatomic) __weak NSTextField *renameTextField; // @synthesize renameTextField;
@property(nonatomic, retain) MSColor *selectedColor; // @synthesize selectedColor;

@end

