//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@protocol _TtP6Sketch35MSRegistrationWindowContentDelegate_;

@interface _TtC6Sketch27MSCloudSignInViewController : NSViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: allowCancellation
    // Error parsing type: , name: state
    // Error parsing type: , name: contentViewController
}

+ (id)storyboardIdentifier;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic) BOOL allowCancellation; // @synthesize allowCancellation;
@property(nonatomic) __weak id <_TtP6Sketch35MSRegistrationWindowContentDelegate_> delegate; // @synthesize delegate;

@end

