//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Sketch21MSComponentPaneAction.h"

@class NSString;

@interface _TtC6Sketch21MSCopyComponentAction : _TtC6Sketch21MSComponentPaneAction
{
}

- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithDocument:(id)arg1;
- (void)doPerformAction:(id)arg1;
- (void)copyComponent:(id)arg1;
@property(nonatomic, readonly) BOOL validate;
@property(nonatomic, readonly) NSString *label;

@end

