//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC14SketchCloudKit23SubscriptionsController : NSObject
{
    // Error parsing type: , name: _subscriptions
    // Error parsing type: , name: log
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

