//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface _TtC17SketchControllers27MSConditionallyOffsetButton : NSButton
{
    // Error parsing type: , name: _yOffsets
}

- (CDUnknownBlockType).cxx_destruct;
- (void)setYOffset:(double)arg1 forOperatingSystemVersion:(CDStruct_2ec95fd7)arg2 backingScaleFactor:(double)arg3;
- (double)yOffsetFor:(double)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

