//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s17SketchControllers35MSCollectionOverlayLayoutAttributesCN.h"

@interface _TtC6Sketch32SelectionOverlayLayoutAttributes : _$s17SketchControllers35MSCollectionOverlayLayoutAttributesCN
{
    // Error parsing type: , name: overrideIndex
}

- (BOOL)isEqual:(id)arg1;
@property(nonatomic) long long overrideIndex; // @synthesize overrideIndex;

@end

