//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC14SketchCloudKitP33_81B92E386B733B2E2D4C717F64CDA9C117DelegateContainer : _TtCs12_SwiftObject
{
    // Error parsing type: , name: delegate
}

@end

