//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface _TtC6Sketch30MSCoEditHealthStatusButtonCell : NSButtonCell
{
    // Error parsing type: , name: rightMargin
    // Error parsing type: , name: textImageMargin
    // Error parsing type: , name: leftMargin
}

- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property(nonatomic, readonly) struct CGSize cellSize;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;

@end

