//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSTextField;

@interface _TtC6Sketch38MSFontEmbeddingAgreementViewController : NSViewController
{
    // Error parsing type: , name: messageField
    // Error parsing type: , name: completionHandler
}

+ (void)presentFromViewController:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)presentIfNecessaryFromViewController:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dismiss:(id)arg1;
- (void)viewWillAppear;
@property(nonatomic) __weak NSTextField *messageField; // @synthesize messageField;

@end

