//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class MSComponentsPaneController;

@interface _TtC6Sketch18ComponentsPaneView : NSView
{
    // Error parsing type: , name: componentsPaneController
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak MSComponentsPaneController *componentsPaneController; // @synthesize componentsPaneController;

@end

