//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Sketch31MSBaseChangeComponentKindAction.h"

@class NSImage, NSString;

@interface _TtC6Sketch36MSChangeTextStyleComponentKindAction : _TtC6Sketch31MSBaseChangeComponentKindAction
{
}

- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithDocument:(id)arg1;
@property(nonatomic, readonly) NSString *tooltip;
- (void)changeToTextStyleComponentKind:(id)arg1;
@property(nonatomic, readonly) NSString *label;
@property(nonatomic, readonly) NSImage *imageForMenu;
@property(nonatomic, readonly) NSString *imageName;

@end

