//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC17SketchControllers26SpacingSnapTargetGenerator : SwiftObject
{
    // Error parsing type: , name: tool
    // Error parsing type: , name: center
    // Error parsing type: , name: spacingCandidates.storage
    // Error parsing type: , name: anchorPointForResizing
    // Error parsing type: , name: visibleRect
    // Error parsing type: , name: coordinateSpace
}

@end

