//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC13SharedEditing23CatchupPhasePatchUpload : _TtCs12_SwiftObject
{
    // Error parsing type: , name: shareID
    // Error parsing type: , name: owner
    // Error parsing type: , name: baseVersion
    // Error parsing type: , name: lastIntegratedPatchID
    // Error parsing type: , name: patches
    // Error parsing type: , name: networkService
    // Error parsing type: , name: callback
    // Error parsing type: , name: numRetries
    // Error parsing type: , name: delegate
    // Error parsing type: , name: numUploadedPatches
    // Error parsing type: , name: progress
    // Error parsing type: , name: firstTime
}

@end

