//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC15SketchRendering16PRTaskDispatcher : _TtCs12_SwiftObject
{
    // Error parsing type: , name: file
    // Error parsing type: , name: drawContext
    // Error parsing type: , name: activeContent
    // Error parsing type: , name: activeBlend
    // Error parsing type: , name: mask
    // Error parsing type: , name: transformStack
    // Error parsing type: , name: currentTransform
    // Error parsing type: , name: nestingLevel
    // Error parsing type: , name: exportArtboardsAsSurfaces
}

@end

