//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@class NSAttributedString;

@interface _TtC6Sketch20MSRecoveryButtonCell : NSButtonCell
{
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
@property(nonatomic, readonly) struct CGSize cellSize;
@property(nonatomic, retain) NSAttributedString *attributedTitle;

@end

