//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Sketch34MSCloudDocumentDownloadsController : NSObject
{
    // Error parsing type: , name: downloads
}

+ (void)setSharedController:(id)arg1;
+ (id)sharedController;
+ (id)documentDownloadChangedNotificationName;
+ (id)documentDownloadChangedNotificationDocumentKey;
+ (id)documentDownloadChangedNotificationShareKey;
- (void).cxx_destruct;
- (id)init;
- (void)downloadDocument:(id)arg1 share:(id)arg2 displayAfterDownload:(BOOL)arg3 displayDownloadProgress:(BOOL)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)cancelAllDownloads;
- (id)downloadErrorForDocumentAtUrl:(id)arg1;
- (id)downloadErrorFor:(id)arg1;
- (void)cancelDownloadForURL:(id)arg1;
- (void)cancelDownloadForShare:(id)arg1;
- (id)downloadProgressForDocumentAtURL:(id)arg1;
- (id)downloadProgressForShare:(id)arg1;
- (BOOL)isDownloadingShare:(id)arg1;

@end

