//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC11BCLayerList22DefaultRowViewRenderer : _TtCs12_SwiftObject
{
    // Error parsing type: , name: borderColor
    // Error parsing type: , name: borderLineWidth
    // Error parsing type: , name: groupRowBackgroundColor
    // Error parsing type: , name: selectedBorderColor
    // Error parsing type: , name: selectedInactiveBorderColor
    // Error parsing type: , name: activeHighlightColor
    // Error parsing type: , name: inactiveHighlightColor
    // Error parsing type: , name: activeSelectionColor
    // Error parsing type: , name: inactiveSelectionColor
    // Error parsing type: , name: activeSubselectionColor
    // Error parsing type: , name: inactiveSubselectionColor
    // Error parsing type: , name: highlightLineWidth
    // Error parsing type: , name: roundCornerRadius
    // Error parsing type: , name: regularRowSelectionInset
}

@end

