//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface _TtC17SketchControllers21MSPointSnappingResult : NSObject
{
    // Error parsing type: , name: result
    // Error parsing type: , name: snaps
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSArray *snaps; // @synthesize snaps;
@property(nonatomic, readonly) struct CGPoint point;

@end

