//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Sketch14CompoundFilter.h"

@interface _TtC6Sketch13KeywordFilter : _TtC6Sketch14CompoundFilter
{
    // Error parsing type: , name: filterString
    // Error parsing type: , name: $__lazy_storage_$_keywords
    // Error parsing type: , name: rawResults
    // Error parsing type: , name: cachedRankedResults
    // Error parsing type: , name: $__lazy_storage_$_locale
}

@end

