//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSPopoverHostViewController.h"

@interface _TtC6Sketch28UploadFlowHostViewController : MSPopoverHostViewController
{
    // Error parsing type: , name: action
    // Error parsing type: , name: displayedStatus
    // Error parsing type: , name: versionOperation
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)attemptFirstErrorRecovery:(id)arg1;
- (void)viewWillAppear;
- (id)initWithCoder:(id)arg1;

@end

