//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Sketch28MSSelectionOverlayController.h"

@interface _TtC6Sketch28MSSelectionOverlayController (Sketch2)
- (struct CGRect)selectionOverlay:(id)arg1 layout:(id)arg2 rectForStackElementAt:(id)arg3;
- (unsigned long long)selectionOverlay:(id)arg1 resizeHandlesMaskForItemAt:(id)arg2;
- (struct CGSize)selectionOverlay:(id)arg1 layout:(id)arg2 sizeForHandleOfKind:(id)arg3 atIndexPath:(id)arg4;
- (BOOL)selectionOverlay:(id)arg1 layout:(id)arg2 shouldHideItemAt:(id)arg3;
- (struct CGAffineTransform)selectionOverlay:(id)arg1 layout:(id)arg2 transformForItemAt:(id)arg3;
- (struct CGRect)selectionOverlay:(id)arg1 layout:(id)arg2 frameForItemAt:(id)arg3;
@end

