//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Sketch28CornerRadiusTextFieldAdaptor : NSObject
{
    // Error parsing type: , name: textFieldValue
    // Error parsing type: , name: inspector
    // Error parsing type: , name: textField
    // Error parsing type: , name: cancellables
}

- (void).cxx_destruct;
- (id)init;
- (void)textFieldChanged:(id)arg1;
@property(nonatomic, copy) id textFieldValue;

@end

