//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSOutlineView;

@interface _TtC6Sketch23ComponentListController : NSViewController
{
    // Error parsing type: , name: outlineView
    // Error parsing type: , name: tree
    // Error parsing type: , name: componentsPaneController
    // Error parsing type: , name: filterString
    // Error parsing type: , name: shouldScrollSelectionToVisible
    // Error parsing type: , name: cachedRowViewRenderer
    // Error parsing type: , name: skipNotifyingDelegateAboutSelectionChange
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidAppear;
- (void)viewDidLoad;
@property(nonatomic) __weak NSOutlineView *outlineView; // @synthesize outlineView;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (id)outlineView:(id)arg1 pasteboardWriterForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;

@end

