//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtCC6Sketch17ComponentTreeLeafP33_7C60325B57B0ACA2AC3D01EE16BD9A9D18CachedPreviewImage : NSObject
{
    // Error parsing type: , name: previewImage
}

- (void).cxx_destruct;
- (id)init;

@end

