//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSToolbar;

@interface _TtC6Sketch34MSAssistantResultsWindowController : NSWindowController
{
    // Error parsing type: , name: configurationItemIdentifier
    // Error parsing type: , name: allAssistantsItemIdentifier
    // Error parsing type: , name: shouldShow
    // Error parsing type: , name: $__lazy_storage_$_resultsController
    // Error parsing type: , name: toolBar
}

+ (id)shared;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)documentDidResignCurrentWithNotification:(id)arg1;
- (void)refreshCurrentDocument;
- (void)documentDidBecomeCurrentWithNotification:(id)arg1;
- (void)displayResultForDocument:(id)arg1;
- (void)keyWindowChanged:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
@property(nonatomic, retain) NSToolbar *toolBar; // @synthesize toolBar;

@end

