//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Sketch18MSRulerContentView.h"

@interface _TtC6Sketch25MSRulerGuideContainerView : _TtC6Sketch18MSRulerContentView
{
    // Error parsing type: , name: formatter
    // Error parsing type: , name: rulerData
    // Error parsing type: , name: temporaryGuidePosition
    // Error parsing type: , name: availableCells
    // Error parsing type: , name: usedCells
    // Error parsing type: , name: temporaryGuideCell
    // Error parsing type: , name: lightAppearanceTextColor
    // Error parsing type: , name: darkAppearanceTextColor
    // Error parsing type: , name: lightAppearanceLabelBackgroundColor
    // Error parsing type: , name: darkAppearanceLabelBackgroundColor
}

- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1;
- (void)layout;
- (void)viewDidChangeEffectiveAppearance;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

