//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSArray, NSButton, NSStackView;
@protocol _TtP6Sketch35MSColorModePickerControllerDelegate_;

@interface _TtC6Sketch27MSColorModePickerController : NSViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: tabColorSolidButton
    // Error parsing type: , name: tabGradientLinearButton
    // Error parsing type: , name: tabGradientRadialButton
    // Error parsing type: , name: tabGradientAngularButton
    // Error parsing type: , name: tabImageButton
    // Error parsing type: , name: tabContainer
    // Error parsing type: , name: modeButtons
    // Error parsing type: , name: colorMode
    // Error parsing type: , name: currentGradientType
    // Error parsing type: , name: allowsFillTypeSelection
    // Error parsing type: , name: styleParts
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (void)modeButtonSelected:(id)arg1;
@property(nonatomic, copy) NSArray *styleParts;
- (void)selectFillType:(unsigned long long)arg1 gradientType:(long long)arg2;
@property(nonatomic, readonly) long long gradientType;
@property(nonatomic, readonly) unsigned long long fillType;
@property(nonatomic) BOOL allowsFillTypeSelection; // @synthesize allowsFillTypeSelection;
@property(nonatomic) long long colorMode; // @synthesize colorMode;
@property(nonatomic, retain) NSStackView *tabContainer; // @synthesize tabContainer;
@property(nonatomic, retain) NSButton *tabImageButton; // @synthesize tabImageButton;
@property(nonatomic, retain) NSButton *tabGradientAngularButton; // @synthesize tabGradientAngularButton;
@property(nonatomic, retain) NSButton *tabGradientRadialButton; // @synthesize tabGradientRadialButton;
@property(nonatomic, retain) NSButton *tabGradientLinearButton; // @synthesize tabGradientLinearButton;
@property(nonatomic, retain) NSButton *tabColorSolidButton; // @synthesize tabColorSolidButton;
@property(nonatomic, retain) id <_TtP6Sketch35MSColorModePickerControllerDelegate_> delegate; // @synthesize delegate;

@end

