//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSView;

@interface _TtC6Sketch26ShapeCornersViewController : NSViewController
{
    // Error parsing type: , name: containerView
    // Error parsing type: , name: currentModeViewController
    // Error parsing type: , name: cancellables
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) __weak NSView *containerView; // @synthesize containerView;

@end

