//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSButton, NSMenu, NSScrollView, NSTextField, _TtC6Sketch23DocumentsCollectionView;

@interface _TtC6Sketch38DocumentsWindowDocumentsViewController : NSViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: collectionScrollView
    // Error parsing type: , name: emptyStateLabel
    // Error parsing type: , name: createFirstDocumentButton
    // Error parsing type: , name: recentDocumentsContextMenu
    // Error parsing type: , name: templatesContextMenu
    // Error parsing type: , name: cachedRecentDocumentItems
    // Error parsing type: , name: cachedTemplateItems
    // Error parsing type: , name: cachedCloudItems
    // Error parsing type: , name: previewImageCache.storage
    // Error parsing type: , name: cloudSharesController
    // Error parsing type: , name: source
    // Error parsing type: , name: delegate
    // Error parsing type: , name: downloadingItems
    // Error parsing type: , name: selectedLocalCloudItem
    // Error parsing type: , name: lastDocumentsLoadDate
    // Error parsing type: , name: refreshOnNextKey
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)cloudUserDidChange:(id)arg1;
- (id)willPresentError:(id)arg1;
- (void)downloadChangedNotificationHandler:(id)arg1;
- (void)cloudAsDefaultDidChange:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (void)clearRecentDocuments:(id)arg1;
- (void)confirm:(id)arg1;
- (void)documentCloudShareDidChange:(id)arg1;
- (void)uploadDidFinish:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)viewDidDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic, retain) NSMenu *templatesContextMenu; // @synthesize templatesContextMenu;
@property(nonatomic, retain) NSMenu *recentDocumentsContextMenu; // @synthesize recentDocumentsContextMenu;
@property(nonatomic, retain) NSButton *createFirstDocumentButton; // @synthesize createFirstDocumentButton;
@property(nonatomic, retain) NSTextField *emptyStateLabel; // @synthesize emptyStateLabel;
@property(nonatomic, retain) NSScrollView *collectionScrollView; // @synthesize collectionScrollView;
@property(nonatomic, retain) _TtC6Sketch23DocumentsCollectionView *collectionView; // @synthesize collectionView;

@end

