//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_TtC6Sketch22ComponentInspectorItem.h"

#import "_TtP6Sketch24MSComponentsPopoverOwner_-Protocol.h"

@interface _TtC6Sketch22ComponentInspectorItem (Sketch) <_TtP6Sketch24MSComponentsPopoverOwner_>
@end

