//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10Assistants20AssistantsRunResults : NSObject
{
    // Error parsing type: , name: assistants
    // Error parsing type: , name: ignore
    // Error parsing type: , name: $__lazy_storage_$_results
    // Error parsing type: , name: $__lazy_storage_$_errors
    // Error parsing type: , name: $__lazy_storage_$_violationCount
    // Error parsing type: , name: $__lazy_storage_$_maxViolationSeverity
    // Error parsing type: , name: $__lazy_storage_$_violations
    // Error parsing type: , name: $__lazy_storage_$_ruleErrors
}

+ (void)setSupportsSecureCoding:(BOOL)arg1;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) long long violationCount;

@end

