//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Sketch14OffsetPathTool : NSObject
{
    // Error parsing type: , name: items
    // Error parsing type: , name: offset
    // Error parsing type: , name: duplicateLayers
    // Error parsing type: , name: historyMaker
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL duplicateLayers; // @synthesize duplicateLayers;
@property(nonatomic) double offset; // @synthesize offset;
- (void)dealloc;

@end

