//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchCloudKit/PSWebSocketDelegate-Protocol.h>

@interface _TtC14SketchCloudKitP33_8D758205BEDACD5355263852682D9D3E16PhoenixWebSocket : NSObject <PSWebSocketDelegate>
{
    // Error parsing type: , name: heartbeat
    // Error parsing type: , name: webSocket
    // Error parsing type: , name: messageHandler
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)init;
- (void)webSocket:(id)arg1 didCloseWithCode:(long long)arg2 reason:(id)arg3 wasClean:(BOOL)arg4;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocket:(id)arg1 didReceiveMessage:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;
- (void)dealloc;

@end

