//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSAttributedString, NSImage, NSString;
@protocol _TtP6Sketch35MSRegistrationWindowContentDelegate_;

@protocol _TtP6Sketch27MSRegistrationWindowContent_
+ (NSString *)storyboardIdentifier;
- (void)registrationWindowDidClickHeaderLink:(id)arg1;
@property(nonatomic) __weak id <_TtP6Sketch35MSRegistrationWindowContentDelegate_> delegate;
@property(nonatomic, readonly) BOOL wantsLicense;
@property(nonatomic) BOOL allowCancellation;
@property(nonatomic, readonly) NSImage *headerImage;
@property(nonatomic, readonly) NSString *headerLinkTitle;
@property(nonatomic, readonly) NSAttributedString *headerDescription;
@property(nonatomic, readonly) NSAttributedString *headerTitle;
@end

