//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class _TtC11SketchModel7Variant;

@protocol _TtP11SketchModel22CurrentVariantDelegate_
- (_TtC11SketchModel7Variant *)currentVariant;
@end

