//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SketchCloudKit/SCKOAuthAPIOperation.h>

#import "BCLicenseOperation-Protocol.h"

@class NSString;

@interface BCCloudLicenseOperation : SCKOAuthAPIOperation <BCLicenseOperation>
{
}

+ (void)refreshLicense:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (Class)licenseClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

