//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <BCLayerList/BCOutlineViewController.h>

@interface BCLayerListViewController : BCOutlineViewController
{
    id _floatingGroupRowItemToScrollToAfterCollapse;
    id _currentlyCollapsingItem;
    id _currentlyExpandingItem;
}

+ (id)itemForExpansionStateNotification:(id)arg1;
@property(retain, nonatomic) id currentlyExpandingItem; // @synthesize currentlyExpandingItem=_currentlyExpandingItem;
@property(retain, nonatomic) id currentlyCollapsingItem; // @synthesize currentlyCollapsingItem=_currentlyCollapsingItem;
@property(retain, nonatomic) id floatingGroupRowItemToScrollToAfterCollapse; // @synthesize floatingGroupRowItemToScrollToAfterCollapse=_floatingGroupRowItemToScrollToAfterCollapse;
- (void).cxx_destruct;
- (void)refreshHeightOfDependentRowsAfterExpansionStateOfGroupItem:(id)arg1 didChangeTo:(BOOL)arg2;
- (long long)nextSiblingRowFromRow:(long long)arg1;
- (void)noteExpansionTransitionState:(unsigned long long)arg1 forItem:(id)arg2;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)outlineViewItemWillExpand:(id)arg1;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemWillCollapse:(id)arg1;
- (void)outlineView:(id)arg1 disclosureTriangleClickedForItem:(id)arg2;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;

@end

