//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSInspectorButton.h"

@class MSFlexibleColor;
@protocol BCMagnifierButtonDelegate;

@interface BCMagnifierButton : MSInspectorButton
{
    id <BCMagnifierButtonDelegate> _delegate;
    MSFlexibleColor *_color;
}

+ (Class)cellClass;
- (void).cxx_destruct;
@property(retain, nonatomic) MSFlexibleColor *color; // @synthesize color=_color;
@property(nonatomic) __weak id <BCMagnifierButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2;
- (id)documentColorSpace;
- (id)initWithFrame:(struct CGRect)arg1;

@end

