//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class BCScreenGrab, MSFlexibleColor;

@interface BCMagnifierWindowContentView : NSView
{
    BCScreenGrab *_screenGrab;
    MSFlexibleColor *_currentColor;
}

@property(retain, nonatomic) MSFlexibleColor *currentColor; // @synthesize currentColor=_currentColor;
@property(retain, nonatomic) BCScreenGrab *screenGrab; // @synthesize screenGrab=_screenGrab;
- (void).cxx_destruct;
- (void)drawMiddlePixel;
- (void)drawPixelLines;
- (void)drawBlackBorder:(id)arg1;
- (void)drawCurrentColorValues;
- (void)drawMagnifiedImage;
- (void)drawRect:(struct CGRect)arg1;

@end

