//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSString;

@protocol BCMutableTreeComparison
- (void)compareOldObject:(id)arg1 againstNewObject:(id)arg2 withName:(NSString *)arg3;
- (void)compareOldArray:(NSArray *)arg1 againstNewArray:(NSArray *)arg2 withName:(NSString *)arg3;
@end

