//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BCRowViewVisuals : NSObject
{
    // Error parsing type: , name: width
    // Error parsing type: , name: regularRowHeight
    // Error parsing type: , name: singleBorderHeight
    // Error parsing type: , name: topAndBottomBorderHeight
    // Error parsing type: , name: scale
    // Error parsing type: , name: renderer
    // Error parsing type: , name: $__lazy_storage_$_groupRowBoundsWithBottomBorder
    // Error parsing type: , name: $__lazy_storage_$_groupRowBoundsWithTopAndBottomBorders
    // Error parsing type: , name: $__lazy_storage_$_plainGroupRowImageWithTopBorder
    // Error parsing type: , name: $__lazy_storage_$_plainGroupRowImageWithBottomBorder
    // Error parsing type: , name: $__lazy_storage_$_plainGroupRowImageWithTopAndBottomBorders
    // Error parsing type: , name: $__lazy_storage_$_highlightedActiveGroupRowImageWithBottomBorder
    // Error parsing type: , name: $__lazy_storage_$_highlightedInactiveGroupRowImageWithBottomBorder
    // Error parsing type: , name: $__lazy_storage_$_highlightedActiveGroupRowImageWithTopAndBottomBorders
    // Error parsing type: , name: $__lazy_storage_$_highlightedInactiveGroupRowImageWithTopAndBottomBorders
    // Error parsing type: , name: $__lazy_storage_$_selectedActiveGroupRowImageWithBottomBorder
    // Error parsing type: , name: $__lazy_storage_$_selectedInactiveGroupRowImageWithBottomBorder
    // Error parsing type: , name: $__lazy_storage_$_selectedActiveGroupRowImageWithTopAndBottomBorders
    // Error parsing type: , name: $__lazy_storage_$_selectedInactiveGroupRowImageWithTopAndBottomBorders
    // Error parsing type: , name: $__lazy_storage_$_regularRowBounds
    // Error parsing type: , name: $__lazy_storage_$_highlightedActiveRegularRowImage
    // Error parsing type: , name: $__lazy_storage_$_highlightedInactiveRegularRowImage
    // Error parsing type: , name: $__lazy_storage_$_selectedActiveRegularRowImageWithBlockyCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedInactiveRegularRowImageWithBlockyCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedActiveRegularRowImageWithRoundCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedInactiveRegularRowImageWithRoundCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedActiveRegularRowImageWithRoundTopCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedInactiveRegularRowImageWithRoundTopCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedActiveRegularRowImageWithRoundBottomCorners
    // Error parsing type: , name: $__lazy_storage_$_selectedInactiveRegularRowImageWithRoundBottomCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedActiveRegularRowImageWithBlockyCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedInactiveRegularRowImageWithBlockyCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedActiveRegularRowImageWithRoundCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedInactiveRegularRowImageWithRoundCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedActiveRegularRowImageWithRoundTopCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedInactiveRegularRowImageWithRoundTopCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedActiveRegularRowImageWithRoundBottomCorners
    // Error parsing type: , name: $__lazy_storage_$_subselectedInactiveRegularRowImageWithRoundBottomCorners
}

- (void).cxx_destruct;
- (id)init;
- (void)updateVisualStateOfRowView:(id)arg1;
- (id)initWithWidth:(double)arg1 regularRowHeight:(double)arg2 singleBorderHeight:(double)arg3 topAndBottomBorderHeight:(double)arg4 scale:(double)arg5;

@end

