//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <BCFoundation/BCSketchInfo.h>

@class NSDictionary, NSString;

@interface BCSketchInfo (BCFoundation)
+ (id)applicationKeys;
+ (id)commitKey;
+ (id)buildNumberKey;
+ (id)variantKey;
+ (id)bundleIdentifierKey;
+ (id)bundleShortVersionKey;
- (void)setVersionCommit:(id)arg1 forMockContext:(id)arg2;
- (id)versionCommitForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *versionCommit;
- (void)setPasteboardVersion:(id)arg1 forMockContext:(id)arg2;
- (id)pasteboardVersionForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *pasteboardVersion;
- (void)setDocumentCompatibilityVersion:(id)arg1 forMockContext:(id)arg2;
- (id)documentCompatibilityVersionForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *documentCompatibilityVersion;
- (void)setDocumentVersion:(id)arg1 forMockContext:(id)arg2;
- (id)documentVersionForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *documentVersion;
- (void)setVariant:(id)arg1 forMockContext:(id)arg2;
- (id)variantForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *variant;
- (id)rootBundleIdentifierForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *rootBundleIdentifier;
- (void)setBundleIdentifier:(id)arg1 forMockContext:(id)arg2;
- (id)bundleIdentifierForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *bundleIdentifier;
- (void)setBundleDisplayName:(id)arg1 forMockContext:(id)arg2;
- (id)bundleDisplayNameForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *bundleDisplayName;
- (void)setBundleName:(id)arg1 forMockContext:(id)arg2;
- (id)bundleNameForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *bundleName;
- (void)setBundleShortVersion:(id)arg1 forMockContext:(id)arg2;
- (id)bundleShortVersionForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *bundleShortVersion;
- (unsigned long long)bundleVersionAsIntegerForMockContext:(id)arg1;
- (void)setBundleVersionAsInteger:(unsigned long long)arg1 forMockContext:(id)arg2;
@property(nonatomic, readonly) unsigned long long bundleVersionAsInteger;
- (void)setBundleVersion:(id)arg1 forMockContext:(id)arg2;
- (id)bundleVersionForMockContext:(id)arg1;
@property(nonatomic, readonly) NSString *bundleVersion;
- (id)metadataForMockContext:(id)arg1;
@property(nonatomic, readonly) NSDictionary *metadata;
- (void)removeMockContext:(id)arg1;
@end

