//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSHoverButton.h"

@interface BCTrialButton : MSHoverButton
{
}

+ (Class)cellClass;
- (struct CGSize)fittingSize;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)viewWillMoveToWindow:(id)arg1;

@end

