//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSFlowBaseAction.h"

@interface MSAddFlowAction : MSFlowBaseAction
{
}

- (id)imageName;
- (BOOL)validate;
- (BOOL)hasDynamicTitle;
- (id)labelForToolbar;
- (id)tooltip;
- (id)label;
- (BOOL)showInToolbar;
- (void)doPerformAction:(id)arg1;
- (void)addFlow:(id)arg1;

@end

