//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSAlignmentEngineWorkings : NSObject
{
    BOOL _snapped;
    unsigned long long _axis;
    double _snapDistance;
    double _snapLocation;
    double _guideStart;
    double _guideEnd;
    struct CGPoint _pointToSnap;
}

@property(readonly, nonatomic) double guideEnd; // @synthesize guideEnd=_guideEnd;
@property(readonly, nonatomic) double guideStart; // @synthesize guideStart=_guideStart;
@property(readonly, nonatomic) double snapLocation; // @synthesize snapLocation=_snapLocation;
@property(readonly, nonatomic) BOOL snapped; // @synthesize snapped=_snapped;
@property(nonatomic) double snapDistance; // @synthesize snapDistance=_snapDistance;
@property(nonatomic) unsigned long long axis; // @synthesize axis=_axis;
@property(nonatomic) struct CGPoint pointToSnap; // @synthesize pointToSnap=_pointToSnap;
- (id)makeGuideForSnapToPoint:(struct CGPoint)arg1;
- (struct CGPoint)snapPoint:(struct CGPoint)arg1 withConstraint:(id)arg2;
- (BOOL)trySnapToTarget:(id)arg1;
- (void)extendGuideToPoint:(struct CGPoint)arg1;
- (void)extendGuideToTarget:(id)arg1;

@end

