//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSDataAction.h"

#import "MSDataMenuApplyDataAction-Protocol.h"

@interface MSApplyDataAction : MSDataAction <MSDataMenuApplyDataAction>
{
}

- (void)doApplyDataToCurrentSelectionRoot:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)validateRootMenuItem:(id)arg1;
- (id)label;
- (void)doPerformAction:(id)arg1;
- (void)doApplyDataToCurrentSelection:(id)arg1;

@end

