//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSAppCenterUserDefaults : NSObject
{
}

+ (void)resetSharedInstance;
+ (id)shared;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)getAppCenterKeyFrom:(id)arg1;
- (void)swapKeys:(id)arg1 newKey:(id)arg2 value:(id)arg3;
- (void)migrateKeys:(id)arg1 forService:(id)arg2;

@end

