//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MSAssetCollectionViewDataSource;

@protocol MSAssetCollectionViewSourceDelegate <NSObject>

@optional
- (void)collectionViewSourceMarkUpdatedIndexesAsRead:(MSAssetCollectionViewDataSource *)arg1;
- (void)collectionViewSource:(MSAssetCollectionViewDataSource *)arg1 getUpdatedIndexes:(void (^)(NSIndexSet *))arg2;
@end

