//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSScrubberDataSource-Protocol.h"
#import "NSScrubberDelegate-Protocol.h"

@class MSAssetCollectionViewDataSource, NSScrubber, NSString, NSTouchBarItem;
@protocol MSAssetPickerScrubberControllerDelegate;

@interface MSAssetPickerScrubberController : NSObject <NSScrubberDelegate, NSScrubberDataSource>
{
    NSString *_identifier;
    MSAssetCollectionViewDataSource *_dataSource;
    id <MSAssetPickerScrubberControllerDelegate> _delegate;
    NSTouchBarItem *_item;
    NSScrubber *_scrubber;
}

@property(retain, nonatomic) NSScrubber *scrubber; // @synthesize scrubber=_scrubber;
@property(retain, nonatomic) NSTouchBarItem *item; // @synthesize item=_item;
@property(retain, nonatomic) id <MSAssetPickerScrubberControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MSAssetCollectionViewDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)scrubber:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (struct CGSize)scrubber:(id)arg1 layout:(id)arg2 sizeForItemAtIndex:(long long)arg3;
- (struct CGSize)fittingAssetScrubberLabelItemSizeForTitle:(id)arg1;
- (id)scrubberItemViewWrapping:(id)arg1;
- (id)colorAssetCollectionLabelWithTitle:(id)arg1;
- (id)scrubberItemViewForAssetAtIndex:(unsigned long long)arg1;
- (id)scrubber:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsForScrubber:(id)arg1;
- (void)reloadData;
- (id)initWithIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

