//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSAssetLibrary, MSAssetLibraryController;

@protocol MSAssetLibraryControllerDelegate <NSObject>
- (void)assetLibraryController:(MSAssetLibraryController *)arg1 libraryChanged:(MSAssetLibrary *)arg2;
@end

