//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSAssetPrefsTableCellView.h"

@class MSAssetPreferenceItem;

@interface MSAssetLibraryTableCellView : MSAssetPrefsTableCellView
{
}

- (void)generatePreview;
@property(readonly, nonatomic) MSAssetPreferenceItem *assetPreferenceItem;
- (void)viewDidChangeBackingProperties;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setObjectValue:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) struct CGRect previewFrame;

@end

