//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDate, NSString;

@interface MSAuthTokenInfo : NSObject <NSCoding>
{
    NSString *_accountId;
    NSString *_authToken;
    NSDate *_startTime;
    NSDate *_expiresOn;
}

@property(readonly, nonatomic) NSDate *expiresOn; // @synthesize expiresOn=_expiresOn;
@property(readonly, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(readonly, copy, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
@property(readonly, copy, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthToken:(id)arg1 accountId:(id)arg2 startTime:(id)arg3 expiresOn:(id)arg4;

@end

