//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSOverrideViewController.h"

#import "MSDataMenuProviderDelegate-Protocol.h"

@class MSImageOverrideView, NSPopUpButton, NSString;

@interface MSBitmapOverrideViewController : MSOverrideViewController <MSDataMenuProviderDelegate>
{
    MSImageOverrideView *_imageView;
    NSPopUpButton *_dataPopUpButton;
}

@property(retain, nonatomic) NSPopUpButton *dataPopUpButton; // @synthesize dataPopUpButton=_dataPopUpButton;
@property(retain, nonatomic) MSImageOverrideView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGRect controlRect;
- (void)dataMenuProvider:(id)arg1 didChooseData:(id)arg2;
- (unsigned long long)supportedDataProviders;
- (id)overrideImage;
- (id)NSImage;
- (id)valueFromControlView:(id)arg1;
- (void)choosePatternImage:(id)arg1;
- (void)build;
- (void)imageViewAction:(id)arg1;
- (id)controlViewForEditingOverride;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

