//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSeparatorConfigurableView.h"

@interface MSBottomSeparatorConfigurableView : MSSeparatorConfigurableView
{
    BOOL _wantsBottomSeparator;
}

@property(nonatomic) BOOL wantsBottomSeparator; // @synthesize wantsBottomSeparator=_wantsBottomSeparator;
- (BOOL)wantsSeparatorBetweenSelfAndView:(id)arg1;

@end

