//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSDictionary, NSString;

@interface MSCloudUser : NSObject <NSSecureCoding>
{
    BOOL _isAdmin;
    BOOL _isVerified;
    NSString *_identifier;
    NSString *_email;
    NSString *_pendingEmail;
    NSString *_name;
    NSString *_webAccessToken;
}

+ (id)userWithIdentifier:(id)arg1 verified:(BOOL)arg2;
+ (BOOL)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *webAccessToken; // @synthesize webAccessToken=_webAccessToken;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) BOOL isVerified; // @synthesize isVerified=_isVerified;
@property(readonly, nonatomic) BOOL isAdmin; // @synthesize isAdmin=_isAdmin;
@property(readonly, copy, nonatomic) NSString *pendingEmail; // @synthesize pendingEmail=_pendingEmail;
@property(readonly, copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)debugDescription;
- (void)parseDictionary:(id)arg1;
@property(readonly, nonatomic) NSDictionary *dictionary;
- (id)verifiedUser;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

