//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchControllers/MSCloudUploadProvider-Protocol.h>

@class NSProgress, NSString, SCKUploadRequest;
@protocol MSCloudExportableDocument;

@interface MSCloudShareXPCUploadController : NSObject <MSCloudUploadProvider>
{
    id <MSCloudExportableDocument> _document;
    SCKUploadRequest *_uploadRequest;
}

@property(readonly, nonatomic) SCKUploadRequest *uploadRequest; // @synthesize uploadRequest=_uploadRequest;
@property(readonly, nonatomic) id <MSCloudExportableDocument> document; // @synthesize document=_document;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL cancelled;
- (void)cancel;
@property(readonly, nonatomic) NSProgress *progress;
- (void)uploadWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithDocument:(id)arg1 uploadUpdatingShare:(id)arg2 ownedByOrganization:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

