//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchRendering/MSCloudManifestMakerDelegate-Protocol.h>

@class MSImmutableDocumentData, MSPresentationRenderer, NSString, NSURL;

@interface MSCloudExporter : NSObject <MSCloudManifestMakerDelegate>
{
    BOOL _drawsAsynchronously;
    BOOL _concurrent;
    BOOL _includePresentationFiles;
    BOOL _includeArtboardImages;
    NSURL *_destinationURL;
    NSString *_name;
    MSImmutableDocumentData *_immutableDocumentData;
    MSPresentationRenderer *_presentationRenderer;
}

+ (id)exportViewportBitmapImageForRequest:(id)arg1;
+ (id)exportBitmapImageForRequest:(id)arg1;
+ (id)imageURLWithHash:(id)arg1 inDirectory:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) MSPresentationRenderer *presentationRenderer; // @synthesize presentationRenderer=_presentationRenderer;
@property(nonatomic) BOOL includeArtboardImages; // @synthesize includeArtboardImages=_includeArtboardImages;
@property(nonatomic) BOOL includePresentationFiles; // @synthesize includePresentationFiles=_includePresentationFiles;
@property(retain, nonatomic) MSImmutableDocumentData *immutableDocumentData; // @synthesize immutableDocumentData=_immutableDocumentData;
@property(nonatomic) BOOL concurrent; // @synthesize concurrent=_concurrent;
@property(nonatomic) BOOL drawsAsynchronously; // @synthesize drawsAsynchronously=_drawsAsynchronously;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
- (id)cloudManifestMaker:(id)arg1 presentationFileMetadataForPage:(id)arg2;
- (id)cloudManifestMaker:(id)arg1 fileMetadataForAncestry:(id)arg2 layerBehavior:(unsigned long long)arg3 atScale:(double)arg4 withSize:(struct CGSize)arg5;
- (id)metadataForPresentationFile:(id)arg1 exportingPage:(id)arg2;
- (id)exportedImageMetadataForRequest:(id)arg1 manifestScale:(double)arg2;
- (id)metadataForDocument:(id)arg1;
- (BOOL)writeJSON:(id)arg1 toFilename:(id)arg2 withError:(id *)arg3;
- (id)createCloudManifestMakerExportingObjects:(id)arg1;
- (BOOL)exportDocumentPreviews;
- (id)exportPresentationFileForPage:(id)arg1 error:(id *)arg2;
- (BOOL)exportPresentationFilesWithObjectIDs:(id)arg1 fileFormats:(id)arg2 error:(id *)arg3;
- (BOOL)exportDocumentWithObjectIDs:(id)arg1 error:(id *)arg2;
- (id)initWithDocument:(id)arg1 name:(id)arg2 localURL:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

