//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchControllers/MSCloudUploadProvider-Protocol.h>
#import <SketchControllers/SCKShareUploadDataSource-Protocol.h>

@class MSImmutableDocumentData, MSWebExporter, NSProgress, NSString, NSURL, SCKOrganization, SCKProject, SCKShare, SCKShareUploadOperation;
@protocol MSCloudExportableDocument, MSCloudUploadProviderDelegate;

@interface MSCloudShareUploadController : NSObject <SCKShareUploadDataSource, MSCloudUploadProvider>
{
    BOOL _cancelled;
    BOOL _operationPending;
    id <MSCloudUploadProviderDelegate> _delegate;
    MSCloudShareUploadController *_previousUpload;
    SCKShare *_existingShare;
    SCKShare *_previousShare;
    SCKOrganization *_organization;
    SCKProject *_project;
    NSProgress *_progress;
    id <MSCloudExportableDocument> _document;
    MSImmutableDocumentData *_dataToUpload;
    NSURL *_localURL;
    NSString *_name;
    MSWebExporter *_webExporter;
    SCKShareUploadOperation *_operation;
}

+ (id)operationQueue;
@property(retain, nonatomic) SCKShareUploadOperation *operation; // @synthesize operation=_operation;
@property(retain, nonatomic) MSWebExporter *webExporter; // @synthesize webExporter=_webExporter;
@property(nonatomic) BOOL operationPending; // @synthesize operationPending=_operationPending;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSURL *localURL; // @synthesize localURL=_localURL;
@property(retain, nonatomic) MSImmutableDocumentData *dataToUpload; // @synthesize dataToUpload=_dataToUpload;
@property(nonatomic) __weak id <MSCloudExportableDocument> document; // @synthesize document=_document;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(readonly, nonatomic) BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(retain, nonatomic) SCKProject *project; // @synthesize project=_project;
@property(retain, nonatomic) SCKOrganization *organization; // @synthesize organization=_organization;
@property(retain, nonatomic) SCKShare *previousShare; // @synthesize previousShare=_previousShare;
@property(retain, nonatomic) SCKShare *existingShare; // @synthesize existingShare=_existingShare;
@property(nonatomic) __weak MSCloudShareUploadController *previousUpload; // @synthesize previousUpload=_previousUpload;
@property(nonatomic) __weak id <MSCloudUploadProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)projectForShareUploadOperation:(id)arg1;
- (void)shareUploadOperation:(id)arg1 exportDocumentWithHandler:(CDUnknownBlockType)arg2;
- (void)shareUploadOperation:(id)arg1 willStartUploadingShare:(id)arg2;
- (id)shareUploadOperation:(id)arg1 fileURLForItemWithHash:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) BOOL finalized;
@property(readonly, nonatomic) SCKShare *newShare;
- (void)cancel;
- (id)loadManifest;
- (void)createShare;
- (void)startUpload;
- (void)dealloc;
- (id)initWithDocument:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

