//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldDelegate.h"

@class NSTextField;

@protocol MSClickableTextFieldDelegate <NSTextFieldDelegate>

@optional
- (void)textFieldDidClick:(NSTextField *)arg1;
- (BOOL)textFieldCanBeClicked:(NSTextField *)arg1;
@end

