//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSATSTypesetter.h>

@class MSConstantBaselineTypesettingSupport;

@interface MSConstantBaselineTypesetter : NSATSTypesetter
{
    MSConstantBaselineTypesettingSupport *_typesettingSupport;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) MSConstantBaselineTypesettingSupport *typesettingSupport; // @synthesize typesettingSupport=_typesettingSupport;
- (void)setLineFragmentRect:(struct CGRect)arg1 forGlyphRange:(struct _NSRange)arg2 usedRect:(struct CGRect)arg3 baselineOffset:(double)arg4;
- (void)willSetLineFragmentRect:(struct CGRect *)arg1 forGlyphRange:(struct _NSRange)arg2 usedRect:(struct CGRect *)arg3 baselineOffset:(double *)arg4;
- (double)paragraphSpacingBeforeGlyphAtIndex:(unsigned long long)arg1 withProposedLineFragmentRect:(struct CGRect)arg2;
- (void)invalidateLayoutFromGlyphLocation:(unsigned long long)arg1;
- (struct _NSRange)constantBaselineGlyphRangeForGlyphLocation:(unsigned long long)arg1;
@property(nonatomic) BOOL useLegacyCustomBaseline;
- (BOOL)usesFontLeading;
- (id)init;

@end

