//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MSComponentsPanelSection : NSObject
{
    NSString *_title;
    NSString *_libraryName;
    NSArray *_symbols;
}

+ (id)sectionWithTitle:(id)arg1 libraryName:(id)arg2 symbols:(id)arg3;
+ (id)sectionsFromSymbolMapping:(id)arg1;
@property(copy, nonatomic) NSArray *symbols; // @synthesize symbols=_symbols;
@property(copy, nonatomic) NSString *libraryName; // @synthesize libraryName=_libraryName;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (BOOL)hasProperSectionContent;
- (id)displayNameForSymbol:(id)arg1;

@end

