//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor;

@interface MSColorConverter : NSObject
{
    NSColor *_color;
}

+ (id)converterWithColor:(id)arg1 colorspace:(id)arg2;
@property(readonly, nonatomic) NSColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)initWithColor:(id)arg1 colorspace:(id)arg2;

@end

