//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSDataSupplier, MSLocalDataSupplier, MSPluginBundle, MSPluginDataSupplier, NSImage, NSString;

@interface MSDataPreferenceItem : NSObject
{
    MSDataSupplier *_data;
    NSImage *_preview;
    NSString *_modificationDate;
    NSString *_secondaryTitle;
}

+ (id)preferenceItemForLocalData:(id)arg1;
@property(retain, nonatomic) NSString *secondaryTitle; // @synthesize secondaryTitle=_secondaryTitle;
@property(readonly, nonatomic) NSString *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(retain, nonatomic) NSImage *preview; // @synthesize preview=_preview;
@property(readonly, nonatomic) MSDataSupplier *data; // @synthesize data=_data;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isPluginEnabled;
@property(readonly, nonatomic) NSImage *pluginBundleIcon;
@property(readonly, nonatomic) MSPluginBundle *pluginBundle;
@property(readonly, nonatomic) BOOL canRevealInFinder;
@property(nonatomic) BOOL enabled;
@property(readonly, nonatomic) BOOL valid;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) MSPluginDataSupplier *pluginData;
@property(readonly, nonatomic) MSLocalDataSupplier *localData;
- (id)initWithData:(id)arg1;

@end

