//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSLocalDataSupplier, NSImage, NSString;

@interface MSDataPreferenceItem : NSObject
{
    MSLocalDataSupplier *_localData;
    NSImage *_preview;
    NSString *_modificationDate;
    NSString *_secondaryTitle;
}

+ (id)preferenceItemForLocalData:(id)arg1;
@property(retain, nonatomic) NSString *secondaryTitle; // @synthesize secondaryTitle=_secondaryTitle;
@property(readonly, nonatomic) NSString *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(retain, nonatomic) NSImage *preview; // @synthesize preview=_preview;
@property(readonly, nonatomic) MSLocalDataSupplier *localData; // @synthesize localData=_localData;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL valid;
@property(readonly, nonatomic) NSString *name;
- (id)initWithLocalData:(id)arg1;

@end

