//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSURL;

@protocol MSDocumentLinting
- (void)lintDocumentAt:(NSURL *)arg1 configFile:(NSURL *)arg2 completionHandler:(void (^)(_TtC15DocumentLinting10LintResult *, NSError *))arg3;
@end

