#import "NSDocument.h"

#import "MSBasicDelegate.h"
#import "MSDocumentDataDelegate.h"
#import "MSPageDelegate.h"
#import "NSMenuDelegate.h"
#import "NSToolbarDelegate.h"
#import "NSWindowDelegate.h"

@class MSActionsController, MSContentDrawViewController, MSDocumentData, MSEventHandlerManager, MSFontList, MSIOSRefreshCollector, MSInspectorController, MSSidebarViewController, MSSplitViewDelegate, MSToolbarConstructor, NSArray, NSDictionary, NSSplitView, NSString, NSTimer, NSView, NSWindow;

@interface MSDocument : NSDocument <NSMenuDelegate, NSToolbarDelegate, NSWindowDelegate, MSBasicDelegate, MSDocumentDataDelegate, MSPageDelegate>
{
    BOOL _hasOpenedImageFile;
    BOOL _nextReadFromURLIsReload;
    NSSplitView *_splitView;
    NSWindow *_documentWindow;
    NSWindow *_messageWindow;
    MSSplitViewDelegate *_splitViewController;
    NSView *_inspectorPlaceholderView;
    NSView *_canvasPlaceholderView;
    MSToolbarConstructor *_toolbarConstructor;
    MSActionsController *_actionsController;
    MSDocumentData *_documentData;
    MSEventHandlerManager *_eventHandlerManager;
    MSInspectorController *_inspectorController;
    MSSidebarViewController *_sidebarController;
    MSIOSRefreshCollector *_refreshCollector;
    MSFontList *_fontList;
    NSArray *_selectedLayers;
    NSDictionary *_collectedSharedObjects;
    NSTimer *_collectedSharedObjectsTimer;
    MSContentDrawViewController *_currentContentViewController;
}

+ (id)currentDocument;
+ (BOOL)isNativeType:(id)arg1;
+ (id)writableTypes;
+ (id)readableTypes;
+ (BOOL)autosavesInPlace;
@property(nonatomic) BOOL nextReadFromURLIsReload; // @synthesize nextReadFromURLIsReload=_nextReadFromURLIsReload;
@property(retain, nonatomic) MSContentDrawViewController *currentContentViewController; // @synthesize currentContentViewController=_currentContentViewController;
@property(nonatomic) BOOL hasOpenedImageFile; // @synthesize hasOpenedImageFile=_hasOpenedImageFile;
@property(retain, nonatomic) NSTimer *collectedSharedObjectsTimer; // @synthesize collectedSharedObjectsTimer=_collectedSharedObjectsTimer;
@property(retain, nonatomic) NSDictionary *collectedSharedObjects; // @synthesize collectedSharedObjects=_collectedSharedObjects;
@property(copy, nonatomic) NSArray *selectedLayers; // @synthesize selectedLayers=_selectedLayers;
@property(retain, nonatomic) MSFontList *fontList; // @synthesize fontList=_fontList;
@property(readonly, nonatomic) MSIOSRefreshCollector *refreshCollector; // @synthesize refreshCollector=_refreshCollector;
@property(retain, nonatomic) MSSidebarViewController *sidebarController; // @synthesize sidebarController=_sidebarController;
@property(retain, nonatomic) MSInspectorController *inspectorController; // @synthesize inspectorController=_inspectorController;
@property(retain, nonatomic) MSEventHandlerManager *eventHandlerManager; // @synthesize eventHandlerManager=_eventHandlerManager;
@property(retain, nonatomic) MSDocumentData *documentData; // @synthesize documentData=_documentData;
@property(retain, nonatomic) MSActionsController *actionsController; // @synthesize actionsController=_actionsController;
@property(retain, nonatomic) MSToolbarConstructor *toolbarConstructor; // @synthesize toolbarConstructor=_toolbarConstructor;
@property(retain, nonatomic) NSView *canvasPlaceholderView; // @synthesize canvasPlaceholderView=_canvasPlaceholderView;
@property(retain, nonatomic) NSView *inspectorPlaceholderView; // @synthesize inspectorPlaceholderView=_inspectorPlaceholderView;
@property(nonatomic) __weak MSSplitViewDelegate *splitViewController; // @synthesize splitViewController=_splitViewController;
@property(retain, nonatomic) NSWindow *messageWindow; // @synthesize messageWindow=_messageWindow;
@property(retain, nonatomic) NSWindow *documentWindow; // @synthesize documentWindow=_documentWindow;
@property(nonatomic) __weak NSSplitView *splitView; // @synthesize splitView=_splitView;
- (void).cxx_destruct;
- (void)debugCountObject:(id)arg1 counts:(id)arg2;
- (void)debugCountObjects:(id)arg1;
- (void)logBuggyBezierPaths;
- (void)determineCurrentArtboard;
- (void)layerSelectionDidChange;
- (void)collectRefreshRect:(struct CGRect)arg1 page:(id)arg2;
- (void)layerTreeLayoutDidChange;
- (void)willRemovePage:(id)arg1;
- (void)didAddPage:(id)arg1;
- (void)didAddArtboard:(id)arg1 toPage:(id)arg2;
- (void)willRemoveArtboard:(id)arg1 fromPage:(id)arg2;
- (void)didUpdateDetailsForArtboard:(id)arg1;
- (void)didUpdateDetailsForPage:(id)arg1;
- (void)currentArtboardDidChange;
- (void)collapseGroupsInLayerList:(id)arg1;
- (void)sliceDidChangeVisibility:(id)arg1;
- (void)changeTextLayerFont:(id)arg1;
- (void)debugStressTestRendering:(id)arg1;
- (void)layerPositionPossiblyChanged;
- (void)startBackgroundCaching;
- (id)addBlankPage;
- (void)toggleClickThrough:(id)arg1;
- (void)findLayer:(id)arg1;
- (void)showCurrentArtboardPreview:(id)arg1;
- (void)redoAction:(id)arg1;
- (void)undoAction:(id)arg1;
- (void)toggleLayersAndInspectorVisibility:(id)arg1;
- (void)toggleInspectorVisibility:(id)arg1;
- (BOOL)isInPresentationMode;
- (void)toggleLayerListVisibility:(id)arg1;
- (void)renameLayer:(id)arg1;
- (void)windowDidExitVersionBrowser:(id)arg1;
- (void)windowDidEnterVersionBrowser:(id)arg1;
- (void)colorMagnifierAction:(id)arg1;
- (BOOL)isRulersVisible;
- (void)toggleRulers;
- (BOOL)currentPopoverHandlesColorMagnifier;
- (void)copyCSSAttributes:(id)arg1;
- (id)pages;
- (id)layersSharingStyle:(id)arg1;
- (id)layerStyles;
- (void)removePage:(id)arg1;
- (void)setCurrentPage:(id)arg1;
- (id)artboards;
- (id)grid;
- (id)document;
- (void)pasteStyle:(id)arg1;
- (void)copyStyle:(id)arg1;
- (void)layoutSettings:(id)arg1;
- (void)gridSettings:(id)arg1;
- (void)setStyleAsDefault:(id)arg1;
- (void)returnToDefaultHandler:(id)arg1;
- (id)defaultHandler;
- (id)setCurrentHandlerKey:(id)arg1;
- (id)toggleHandlerKey:(id)arg1;
- (void)reloadInspector;
- (void)reloadLayerList;
- (void)refreshViewsWithMask:(unsigned long long)arg1;
- (void)refreshOfType:(unsigned long long)arg1 rect:(struct CGRect)arg2;
- (id)rootDelegate;
- (void)deleteArtboards:(id)arg1;
- (void)closePath:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (id)currentVerticalRulerData;
- (id)currentHorizontalRulerData;
- (void)zoomValueDidChange;
- (void)syncSharedObjects:(id)arg1;
- (void)documentData:(id)arg1 syncSharedObject:(id)arg2;
- (void)documentData:(id)arg1 didChangeToPage:(id)arg2;
- (BOOL)inspectorIsMain;
- (void)selectToolbarItemWithIdentifier:(id)arg1;
- (id)closestVisibleIdentifierInToolbarForIdentifier:(id)arg1;
- (void)reversePath:(id)arg1;
- (void)flagsChanged:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (id)currentHandlerKey;
- (id)currentHandler;
- (void)enableInteractionFrom:(id)arg1;
- (void)toggleSliceInteraction:(id)arg1;
- (void)toggleLayerInteraction:(id)arg1;
- (void)toggleLayerHighlight:(id)arg1;
- (void)toggleSelection:(id)arg1;
- (void)lockLayer:(id)arg1;
- (void)toggleArtboardShadow:(id)arg1;
- (void)togglePixelLines:(id)arg1;
- (void)toggleAlignmentGuides:(id)arg1;
- (void)validateMenuItemTitle:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)layerWouldOverlapExistingLayer:(id)arg1 inGroup:(id)arg2;
- (void)offsetLayerIfNecessary:(id)arg1 forInsertingInGroup:(id)arg2;
- (void)addLayer:(id)arg1 changeName:(BOOL)arg2;
- (void)addLayer:(id)arg1;
- (id)findCurrentArtboardGroup;
- (void)coalescedDetermineArtboardNotification:(id)arg1;
- (void)putSelectionBackInCanvasIfPossible;
- (void)coalescedSelectionDidChangeNotification:(id)arg1;
- (id)findSelectedLayers;
- (id)currentPage;
- (void)exportPDFBook:(id)arg1;
- (void)exportSliceLayers:(id)arg1;
- (id)allExportableLayers;
- (void)exportEnabledSliceLayers:(id)arg1;
- (void)export:(id)arg1;
- (id)selectedLayersOfClass:(Class)arg1;
- (void)sendMessageToRootObject:(unsigned long long)arg1;
- (void)returnToNormalHandler;
- (void)currentHandlerChanged;
@property(nonatomic) double zoomValue; // @dynamic zoomValue;
@property(nonatomic) struct CGPoint scrollOrigin; // @dynamic scrollOrigin;
- (id)windowNibName;
- (id)toolbar;
- (BOOL)shouldCreateToolbar;
- (void)windowControllerDidLoadNib:(id)arg1;
- (void)loadLayerListPanel;
- (void)loadInspectorPanel;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)awakeFromNib;
- (void)wireDocumentDataToUI;
- (id)currentView;
- (id)printOperationWithSettings:(id)arg1 error:(id *)arg2;
- (void)windowWillClose:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidEndSheet:(id)arg1;
- (void)windowWillBeginSheet:(id)arg1;
- (id)window;
- (void)dealloc;
- (void)close;
- (void)setDelegatesToNil;
- (id)actionWithName:(id)arg1;
- (id)actions;
- (void)createActions;
- (id)init;
- (id)exportFramer;
- (void)hideMessage:(id)arg1;
- (void)hideMessage;
- (void)displayMessage:(id)arg1 timeout:(double)arg2;
- (void)displayMessage:(id)arg1;
- (void)showMessage:(id)arg1;
- (void)stopAccessingFolderToken:(id)arg1;
- (id)startAccessingFolder:(id)arg1 tokenName:(id)arg2;
- (id)dataForRequest:(id)arg1 ofType:(id)arg2;
- (void)saveSlice:(id)arg1 toFile:(id)arg2;
- (id)sliceForArtboardOrSlice:(id)arg1;
- (void)saveArtboardOrSlice:(id)arg1 toFile:(id)arg2;
- (id)sliceForRect:(id)arg1;
- (id)askForUserInput:(id)arg1 ofType:(long long)arg2 initialValue:(id)arg3;
- (id)askForUserInput:(id)arg1 initialValue:(id)arg2;
- (void)warnAboutOldVersion;
- (BOOL)askToOpenDocumentRepairingMetadata;
- (BOOL)askToOpenDocumentWithMissingFonts:(id)arg1;
- (void)alertDocumentIsWrongSize;
- (void)alertDocumentIsTooNew;
- (void)resetImportedDocument:(id)arg1;
- (BOOL)readImageFromPath:(id)arg1 error:(id *)arg2;
- (id)addImageLayerFromPath:(id)arg1 toGroup:(id)arg2 fitPixels:(BOOL)arg3 error:(id *)arg4;
- (BOOL)readFromDocumentWrapper:(id)arg1 ofType:(id)arg2 wasMigrated:(BOOL)arg3 error:(id *)arg4;
- (BOOL)processValidationCode:(unsigned long long)arg1 wrapper:(id)arg2 missingFonts:(id)arg3;
- (id)migrateWithXPCFromURL:(id)arg1 error:(id *)arg2;
- (BOOL)validateWithXPCAtURL:(id)arg1 wrapper:(id)arg2;
- (BOOL)validateLocallyWithWrapper:(id)arg1;
- (BOOL)readDocumentFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)revertToContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readEPSFromURL:(id)arg1;
- (BOOL)readPDFFromURL:(id)arg1;
- (BOOL)readSVGFromURL:(id)arg1;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 originalContentsURL:(id)arg4 error:(id *)arg5;
- (BOOL)canAsynchronouslyWriteToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

