//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol MSDragLayerToolUserInterface <NSObject>
- (void)setUndoActionName:(NSString *)arg1;
- (void)selectLayers:(NSArray *)arg1;
@end

