//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSFeatureAvailability : NSObject
{
}

+ (BOOL)builtInRemoteLibrariesEnabled;
+ (void)setBuiltInRemoteLibrariesEnabled:(BOOL)arg1;
+ (BOOL)shouldArchiveMSAttributedStringAsJSON;
+ (void)setIsComponentsPanelEnabled:(BOOL)arg1;
+ (BOOL)isComponentsPanelEnabled;
+ (void)setFlowsEnabled:(BOOL)arg1;
+ (BOOL)flowsEnabled;
+ (void)setDataSuppliersEnabled:(BOOL)arg1;
+ (BOOL)dataSuppliersEnabled;
+ (void)setLibraryStylesEnabled:(BOOL)arg1;
+ (BOOL)libraryStylesEnabled;
+ (void)setFeature:(id)arg1 enabled:(BOOL)arg2;
+ (BOOL)isFeatureEnabled:(id)arg1;
+ (void)enableFeatureAvailability;

@end

