//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSMenuDelegate-Protocol.h"

@class MSColor, NSArray, NSMenu, NSString;
@protocol MSFrequentColorsControllerDelegate;

@interface MSFrequentColorsController : NSObject <NSMenuDelegate>
{
    MSColor *_color;
    NSArray *_frequentColors;
    long long _colorModel;
    id <MSFrequentColorsControllerDelegate> _delegate;
    NSMenu *_menu;
}

+ (id)menuItemForColorCounter:(id)arg1 target:(id)arg2 action:(SEL)arg3 documentColorSpace:(id)arg4 colorModel:(long long)arg5;
+ (id)menuItemAttributedTitleForColorCounter:(id)arg1 colorModel:(long long)arg2;
+ (id)previewImageForColorCounter:(id)arg1 documentColorSpace:(id)arg2;
@property(retain, nonatomic) NSMenu *menu; // @synthesize menu=_menu;
@property(nonatomic) __weak id <MSFrequentColorsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long colorModel; // @synthesize colorModel=_colorModel;
@property(copy, nonatomic) NSArray *frequentColors; // @synthesize frequentColors=_frequentColors;
@property(retain, nonatomic) MSColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (void)showMenuAtLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (void)frequentColorPicked:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

