//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchRendering/MSRenderer-Protocol.h>

@class MSImmutableGradient, MSModelObjectCacheGeneration, MSRenderingContext;

@protocol MSGradientRenderer <MSRenderer>
- (void)drawGradient:(MSImmutableGradient *)arg1 inRect:(struct CGRect)arg2 forBorderThickness:(double)arg3 context:(MSRenderingContext *)arg4 cacheKey:(MSModelObjectCacheGeneration *)arg5;
@end

