//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchModel/MSPointArray.h>

@protocol MSGradientPointArrayDelegate;

@interface MSGradientPointArray : MSPointArray
{
    id <MSGradientPointArrayDelegate> _delegate;
}

@property(nonatomic) __weak id <MSGradientPointArrayDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)replacePointAtIndex:(unsigned long long)arg1 withPoint:(struct CGPoint)arg2;

@end

