//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface MSHoverButtonCell : NSButtonCell
{
}

- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (id)imageFromImage:(id)arg1 withState:(long long)arg2 hovering:(BOOL)arg3;
- (id)init;

@end

