//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSImageLayerImporter : NSObject
{
}

+ (BOOL)fileIsVectorFormat:(id)arg1;
+ (id)importerForPath:(id)arg1;
+ (id)importLayerFromPath:(id)arg1;
+ (id)layerWithContentsOfPath:(id)arg1 mode:(unsigned long long)arg2;

@end

