//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SketchModel/MSImmutableHotspotLayer.h>

#import <SketchControllers/MSImmutableLayerPreviewability-Protocol.h>

@interface MSImmutableHotspotLayer (Preview) <MSImmutableLayerPreviewability>
- (void)refreshPreviewImagesWithDocumentData:(id)arg1;
- (BOOL)previewImagesRequireRefreshWithDocumentData:(id)arg1;
- (void)drawPreviewInRect:(struct CGRect)arg1 selected:(BOOL)arg2 bezier:(id)arg3;
@end

