//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchModel/MSImmutableStyleFill.h>

@interface MSImmutableStyleFill (SVGExport)
- (void)addSVGAttributes:(id)arg1 exporter:(id)arg2;
- (id)addPatternLink:(id)arg1;
- (id)addStretchedPattern:(id)arg1 exporter:(id)arg2;
- (id)addFilledOrFitPattern:(id)arg1 exporter:(id)arg2 type:(long long)arg3;
- (id)addTiledPattern:(id)arg1 scale:(double)arg2 exporter:(id)arg3;
- (void)addUseWrapperToPattern:(id)arg1 withImageWrapper:(id)arg2 scaleX:(double)arg3 scaleY:(double)arg4;
- (id)addImageDefinition:(id)arg1 exporter:(id)arg2;
@end

