//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SketchControllers/MSObjectCounter.h>

@class MSImageData, NSString;

@interface MSImageCounter : MSObjectCounter
{
    NSString *_sizeString;
}

@property(retain, nonatomic) NSString *sizeString; // @synthesize sizeString=_sizeString;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) MSImageData *imageData;

@end

