//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutableHotspotLayer.h"

@interface MSImmutableHotspotLayer : _MSImmutableHotspotLayer
{
}

+ (id)defaultName;
+ (unsigned long long)traits;
- (void)performInitEmptyObject;
- (BOOL)isLayerExportable;
- (Class)overrideViewControllerClassForOverridePoint:(id)arg1;
- (void)refreshPreviewImagesWithDocumentData:(id)arg1 cache:(id)arg2;
- (BOOL)previewImagesRequireRefreshWithDocumentData:(id)arg1 cache:(id)arg2;
- (void)drawPreviewInRect:(struct CGRect)arg1 documentData:(id)arg2 selected:(BOOL)arg3 bezier:(id)arg4;
- (id)flowDestination;
- (id)overridePointsWithParent:(id)arg1;

@end

