//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutableCurvePoint.h"

#import "MSCurvePoint.h"

@class NSString;

@interface MSImmutableCurvePoint : _MSImmutableCurvePoint <MSCurvePoint>
{
}

@property(readonly, nonatomic) BOOL isRounded;
@property(readonly, nonatomic) BOOL isStraight;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

