//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSImmutableShapeGroup.h"

#import "MSShapeGroup.h"

@class NSBezierPath, NSDictionary, NSObject<NSCopying><NSCoding>, NSString;

@interface MSImmutableShapeGroup : _MSImmutableShapeGroup <MSShapeGroup>
{
    NSBezierPath *_bezierPathWithTransformsForMasking;
}

+ (id)bezierPathForEndDecorationOnPath:(id)arg1 decorationType:(unsigned long long)arg2;
+ (id)bezierPathForStartDecorationOnPath:(id)arg1 decorationType:(unsigned long long)arg2;
+ (unsigned long long)traits;
+ (void)initialize;
+ (id)lineDecoration;
+ (id)openArrowDecoration;
+ (id)closedArrowDecoration;
+ (id)pathForDecorationType:(unsigned long long)arg1;
+ (void)cacheDecorations;
@property(retain, nonatomic) NSBezierPath *bezierPathWithTransformsForMasking; // @synthesize bezierPathWithTransformsForMasking=_bezierPathWithTransformsForMasking;
- (void).cxx_destruct;
- (id)bezierPathForEndDecorationOnPath:(id)arg1;
- (id)bezierPathForStartDecorationOnPath:(id)arg1;
@property(readonly, nonatomic) NSBezierPath *decoratedBezierPathInBounds;
- (id)bezierPathOfSubPath:(id)arg1 inRect:(struct CGRect)arg2;
@property(readonly, nonatomic) NSBezierPath *bezierPathInBounds;
- (id)_bezierPathInSize:(struct CGSize)arg1;
- (void)applyPropertiesToBezier:(id)arg1;
@property(readonly, nonatomic) NSBezierPath *bezierPath;
@property(readonly, nonatomic) NSBezierPath *bezierPathWithTransforms;
- (BOOL)includeChildrenInCalculatingStyleSize;
- (struct CGRect)calculateInfluenceRectForBounds;
- (BOOL)canSkipAdvancedClipForStrokes;
- (id)defaultName;
- (id)bezierPathInRect:(struct CGRect)arg1;
@property(readonly, nonatomic) BOOL isPartOfClippingMask;
@property(readonly, nonatomic) BOOL hasDecorations;
- (void)objectDidInit;
- (id)refreshPreviewBezierPath;
- (id)possibleOverridesInDocument:(id)arg1 skipping:(id)arg2;
- (BOOL)differsFromLayer:(id)arg1;
- (void)migratePropertiesFromV51OrEarlierWithCoder:(id)arg1;
- (Class)rendererClass;
- (id)addContentToElement:(id)arg1 attributes:(id)arg2 exporter:(id)arg3;
- (id)addGroupContentToElement:(id)arg1 attributes:(id)arg2 exporter:(id)arg3;
- (void)addSVGAttributes:(id)arg1 exporter:(id)arg2;
- (void)addDecorationToParent:(id)arg1 exporter:(id)arg2;
- (id)addMaskToElement:(id)arg1 exporter:(id)arg2;
- (void)simplifyPathElement:(id)arg1 exporter:(id)arg2;
- (void)addPathDefinitionToDocument:(id)arg1;
- (id)svgPathAttribute:(id)arg1;
- (void)appendBaseTranslation:(id)arg1 exporter:(id)arg2;
- (BOOL)requiresPathDefinition:(id)arg1;
- (id)svgStyle:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) struct CGAffineTransform CGTransformForFrame;
@property(readonly, nonatomic) struct CGRect bounds;
@property(readonly, nonatomic) long long clippingMaskMode;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) id <MSExportOptions> exportOptionsGeneric;
@property(readonly, nonatomic) id <MSRect> frameGeneric;
@property(readonly, nonatomic) BOOL hasClickThrough;
@property(readonly, nonatomic) BOOL hasClippingMask;
@property(readonly, nonatomic) BOOL hasTransforms;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct BCEdgePaddings influenceRectEdgePaddingsThatCascadeToContainedLayers;
@property(readonly, nonatomic) BOOL isFlippedHorizontal;
@property(readonly, nonatomic) BOOL isFlippedVertical;
@property(readonly, nonatomic) BOOL isLayerExportable;
@property(readonly, nonatomic) BOOL isLocked;
@property(readonly, nonatomic) BOOL isVisible;
@property(readonly, nonatomic) long long layerListExpandedType;
@property(readonly, nonatomic) id <MSArray> layersGeneric;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, nonatomic) BOOL nameIsFixed;
@property(readonly, copy, nonatomic) NSObject<NSCopying><NSCoding> *objectID;
@property(readonly, nonatomic) struct CGPoint origin;
@property(readonly, nonatomic) NSString *originalObjectID;
@property(readonly, nonatomic) struct CGRect rect;
@property(readonly, nonatomic) double rotation;
@property(readonly, nonatomic) NSObject<NSCopying><NSCoding> *sharedObjectID;
@property(readonly, nonatomic) BOOL shouldBreakMaskChain;
@property(readonly, nonatomic) id <MSStyle> styleGeneric;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSDictionary *userInfo;
@property(readonly, nonatomic) unsigned long long windingRule;

@end

