//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchModel/_MSImmutableSharedStyle.h>

#import <SketchModel/BCSortable-Protocol.h>

@class MSImmutableStyle, NSString;

@interface MSImmutableSharedStyle : _MSImmutableSharedStyle <BCSortable>
{
}

+ (id)defaultName;
@property(readonly, nonatomic) MSImmutableStyle *style;
- (id)encodeForManifest:(id)arg1 earlierSlugs:(id)arg2 includingFiles:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *name;
@property(readonly) Class superclass;

@end

