//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MSImageLayerImporter : NSObject
{
}

+ (BOOL)fileIsVectorFormat:(id)arg1;
+ (id)importerForPath:(id)arg1;
+ (id)importLayerFromPath:(id)arg1;
+ (id)layerWithContentsOfPath:(id)arg1 mode:(unsigned long long)arg2;

@end

