//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSInlineUpDownTextField.h"

@class NSClickGestureRecognizer, NSMenu, NSPressGestureRecognizer;

@interface MSInlineUpDownTextFieldWithMenu : MSInlineUpDownTextField
{
    NSPressGestureRecognizer *_pressRecognizer;
    NSClickGestureRecognizer *_clickRecognizer;
    NSMenu *_popupMenu;
}

@property(retain, nonatomic) NSMenu *popupMenu; // @synthesize popupMenu=_popupMenu;
- (void).cxx_destruct;
- (void)clickShowInlineMenu:(id)arg1;
- (void)pressShowInlineMenu:(id)arg1;
- (void)doShowMenu;
- (void)updateUpDownLabel;
- (id)clickRecognizer;
- (id)pressRecognizer;
- (id)createUpDownController;

@end

