//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSInsertLayerEventHandler.h"

@class MSTextLayer;

@interface MSInsertTextEventHandler : MSInsertLayerEventHandler
{
    MSTextLayer *_textLayer;
}

@property(retain, nonatomic) MSTextLayer *textLayer; // @synthesize textLayer=_textLayer;
- (void).cxx_destruct;
- (void)drawRectPreview;
- (BOOL)allowsSwitchToInsertAction;
- (id)toolbarIdentifier;
- (struct CGRect)rectForInsertingTextLayerAtPoint:(struct CGPoint)arg1;
- (void)selectTextLayerAndEdit:(id)arg1;
- (id)textLayerAtPoint:(struct CGPoint)arg1 zoomValue:(double)arg2;
- (BOOL)tryToEditExistingTextLayerAtPoint:(struct CGPoint)arg1 zoomValue:(double)arg2;
- (id)textLayerWithRect:(struct CGRect)arg1 behavior:(long long)arg2;
- (id)performActionWithRect:(struct CGRect)arg1 fromLayer:(id)arg2 constrainProportions:(BOOL)arg3;
- (void)handleDrag:(id)arg1;
- (void)handlerGotFocus;

@end

