//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseInsertAction.h"

@interface MSInsertLineAction : MSBaseInsertAction
{
}

- (unsigned short)shortcutCharacter;
- (id)imageName;
- (id)tooltip;
- (BOOL)isSelectable;
- (id)eventHandlerName;
- (void)doPerformAction:(id)arg1;
- (id)lineShapeFrom:(struct CGPoint)arg1 to:(struct CGPoint)arg2;
- (void)insertLine:(id)arg1;

@end

