//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class NSString;
@protocol MSInspectorTableViewManagerDelegate;

@interface MSInspectorTableViewManager : NSObject <NSTableViewDataSource, NSTableViewDelegate>
{
    id <MSInspectorTableViewManagerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MSInspectorTableViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)refreshTableView:(id)arg1 ifNecessary:(id)arg2;
- (id)visibleItemsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didRemoveRowView:(id)arg2 forRow:(long long)arg3;
- (void)tableView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (BOOL)wantsSeparatorForRow:(unsigned long long)arg1;
- (id)itemIndexPathForRowIndex:(unsigned long long)arg1;
- (id)sectionItemIndex:(unsigned long long *)arg1 forRowIndex:(unsigned long long)arg2;
- (id)sectionForRow:(unsigned long long)arg1;
- (id)sections;
- (void)manageTableView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

