//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MSTreeDiff, NSArray;

@protocol MSInspectorChildController
- (void)refreshIfNecessary:(MSTreeDiff *)arg1;
- (void)selectionDidChangeTo:(NSArray *)arg1;
- (void)prepareForDisplay;

@optional
- (void)layerPositionPossiblyChanged;
@end

