//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@class NSColor;

@interface MSInspectorPushButtonCell : NSButtonCell
{
    BOOL _fakeReturnButtonLook;
}

@property(nonatomic) BOOL fakeReturnButtonLook; // @synthesize fakeReturnButtonLook=_fakeReturnButtonLook;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (long long)interiorBackgroundStyle;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)drawBezelWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)drawAsReturnButton;
@property(readonly, nonatomic) NSColor *buttonHighlightedColor;
@property(readonly, nonatomic) NSColor *buttonOnColor;
- (id)namedButtonColor;

@end

