//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSJSONDataReference.h"

@interface MSJSONOriginalDataReference : MSJSONDataReference
{
}

- (id)initWithJSONDecoder:(id)arg1;
- (void)encodeAsJSON:(id)arg1;

@end

