//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSKeyedArchiver.h>

@class MSBaseArchiver;

@interface MSKeyedArchiverHelper : NSKeyedArchiver
{
    MSBaseArchiver *_archiver;
}

@property(nonatomic) __weak MSBaseArchiver *archiver; // @synthesize archiver=_archiver;
- (void).cxx_destruct;
- (void)encodeObject:(id)arg1 forKey:(id)arg2;

@end

