//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSingletonObject.h"

@class NSDictionary;

@interface MSKeyBindings : CHSingletonObject
{
    NSDictionary *_shortcutMap;
}

@property(readonly, nonatomic) NSDictionary *shortcutMap; // @synthesize shortcutMap=_shortcutMap;
- (void).cxx_destruct;
- (id)defaultKeyBindingsPath;
- (id)userKeyBindingsPath;
- (id)init;

@end

