//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSLayoutElement : NSObject
{
    // Error parsing type: , name: bounds
    // Error parsing type: , name: position
    // Error parsing type: , name: anchorPoint
    // Error parsing type: , name: children
    // Error parsing type: , name: parent
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) double fillFactor;

@end

