//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "MSInspectorSection.h"
#import "NSMenuDelegate.h"

@class MSSharedStylesInspectorSection, NSArray, NSButton, NSNumberFormatter, NSString, NSTextField, NSView;

@interface MSLayerInspectorViewController : NSViewController <MSInspectorSection, NSMenuDelegate>
{
    BOOL _shouldShowPositions;
    BOOL _shouldShowSharedStyles;
    BOOL _shouldShowLayerSpecificProperties;
    BOOL _shouldShowBlendingProperties;
    BOOL _needsUpdatePositionAndSizeFields;
    NSArray *_layers;
    NSView *_positionView;
    NSView *_lineView;
    NSTextField *_xTextField;
    NSTextField *_yTextField;
    NSTextField *_widthTextField;
    NSTextField *_heightTextField;
    NSButton *_lockProportionsButton;
    MSSharedStylesInspectorSection *_sharedObjectsController;
    NSArray *_layerInspectorControllers;
    NSNumberFormatter *_numberFormatter;
}

@property(readonly, nonatomic) BOOL needsUpdatePositionAndSizeFields; // @synthesize needsUpdatePositionAndSizeFields=_needsUpdatePositionAndSizeFields;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(retain, nonatomic) NSArray *layerInspectorControllers; // @synthesize layerInspectorControllers=_layerInspectorControllers;
@property(retain, nonatomic) MSSharedStylesInspectorSection *sharedObjectsController; // @synthesize sharedObjectsController=_sharedObjectsController;
@property(nonatomic) BOOL shouldShowBlendingProperties; // @synthesize shouldShowBlendingProperties=_shouldShowBlendingProperties;
@property(nonatomic) BOOL shouldShowLayerSpecificProperties; // @synthesize shouldShowLayerSpecificProperties=_shouldShowLayerSpecificProperties;
@property(nonatomic) BOOL shouldShowSharedStyles; // @synthesize shouldShowSharedStyles=_shouldShowSharedStyles;
@property(nonatomic) BOOL shouldShowPositions; // @synthesize shouldShowPositions=_shouldShowPositions;
@property(nonatomic) __weak NSButton *lockProportionsButton; // @synthesize lockProportionsButton=_lockProportionsButton;
@property(nonatomic) __weak NSTextField *heightTextField; // @synthesize heightTextField=_heightTextField;
@property(nonatomic) __weak NSTextField *widthTextField; // @synthesize widthTextField=_widthTextField;
@property(nonatomic) __weak NSTextField *yTextField; // @synthesize yTextField=_yTextField;
@property(nonatomic) __weak NSTextField *xTextField; // @synthesize xTextField=_xTextField;
@property(retain, nonatomic) NSView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) NSView *positionView; // @synthesize positionView=_positionView;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (void).cxx_destruct;
- (void)colorMagnifierAction:(id)arg1;
- (BOOL)canHandleColorMagnifierAction;
- (BOOL)hasLineShapeLayer;
- (BOOL)layerIsGroup;
- (id)views;
- (id)valueForUndefinedKey:(id)arg1;
- (id)document;
- (void)refreshAction:(id)arg1;
- (id)inspectorsWithProperContent;
- (id)layerOrContentsOfLayer:(id)arg1 ifKindOfClass:(Class)arg2;
- (id)sharedObjectsSection;
- (void)layerWithSharedStyleDidChange;
- (void)beginRenameSharedObject:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)changeTextLayerFont:(id)arg1;
- (struct CGRect)boundsForParentOf:(id)arg1;
- (long long)anchorFromString:(id)arg1 axis:(unsigned long long)arg2;
- (void)setLayerSizeFromString:(id)arg1 onAxis:(unsigned long long)arg2;
- (void)setHeightAction:(id)arg1;
- (void)setWidthAction:(id)arg1;
- (void)setYAction:(id)arg1;
- (void)setXAction:(id)arg1;
- (double)layerSizeOnAxis:(unsigned long long)arg1;
- (double)rulerOriginXForLayer:(id)arg1;
- (double)rulerOriginYForLayer:(id)arg1;
- (double)absoluteYForLayers;
- (double)absoluteXForLayers;
- (void)setValue:(double)arg1 forField:(id)arg2;
- (void)refreshBindingsOnShape:(id)arg1;
- (void)clearPositionAndSizeFields;
- (void)setNeedsUpdatePositionAndSizeFields;
- (void)updatePositionAndSizeFields;
- (void)layerPositionPossiblyChanged;
- (BOOL)wantsSeparatorBetweenView:(id)arg1 andView:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

