//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSLayerGroup.h"

#import "MSLayerGroup.h"

@class NSArray;

@interface MSLayerGroup : _MSLayerGroup <MSLayerGroup>
{
    long long _preCalculatedHasSelectedLayer;
    unsigned long long _disableAutomaticScalingCounter;
}

+ (BOOL)groupBoundsShouldBeIntegral;
+ (struct CGRect)groupBoundsForContainer:(id)arg1;
+ (void)moveLayers:(id)arg1 intoGroup:(id)arg2;
+ (id)groupFromLayers:(id)arg1;
@property(nonatomic) unsigned long long disableAutomaticScalingCounter; // @synthesize disableAutomaticScalingCounter=_disableAutomaticScalingCounter;
@property(nonatomic) long long preCalculatedHasSelectedLayer; // @synthesize preCalculatedHasSelectedLayer=_preCalculatedHasSelectedLayer;
- (id)candidatesForMasking;
- (id)children;
- (id)layerWithID:(id)arg1;
- (void)resizeChildLayer:(id)arg1 oldParentSize:(struct CGSize)arg2;
- (void)rectDidChange:(id)arg1 fromRect:(struct CGRect)arg2;
@property(readonly, nonatomic) BOOL isAutomaticScalingEnabled;
- (void)disableAutomaticScalingInBlock:(CDUnknownBlockType)arg1;
- (void)multiplyBy:(double)arg1;
- (BOOL)resizeToFitChildrenWithOption:(long long)arg1;
- (struct CGRect)requiredRect;
- (void)setIsHovering:(BOOL)arg1;
- (BOOL)isOpenForSelectionWithOptions:(unsigned long long)arg1;
- (BOOL)isSelectableOnCanvasWithOptions:(unsigned long long)arg1;
- (void)deselectAllLayers;
- (void)selectLayers:(id)arg1;
- (BOOL)containsSelectedItemIncludingSelf:(BOOL)arg1;
- (BOOL)shouldAutoresizeChildrenAfterResize;
- (void)layerDidResize;
- (void)layerWillResize;
- (void)setIsSelected:(BOOL)arg1;
- (BOOL)isExpanded;
- (void)deselectLayerAndParent;
- (void)refreshOverlay;
- (void)moveInLayerTreeInBlock:(CDUnknownBlockType)arg1;
- (BOOL)shouldStripShadowsAndInnerShadow;
- (void)setStyle:(id)arg1;
- (id)bezierPath;
- (id)defaultStyle;
- (id)parentGroupRecursive;
- (void)objectDidInit;
- (void)performInitEmptyObject;
- (BOOL)handleDoubleClick;
- (id)inspectorViewControllerNames;
- (void)drawHoverWithZoom:(double)arg1 cache:(id)arg2;
- (void)prepareAsMaskContainer;
- (id)unselectedPreviewImage;
- (id)selectedPreviewImage;
- (BOOL)expandableInLayerList;
- (void)enumerateLayersAvoidingFaultingWithOptions:(unsigned long long)arg1 passingTest:(CDUnknownBlockType)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)moveTransformsToChildren:(id)arg1;
- (id)ungroupReturningNextUngroupGroup;
- (BOOL)hasStyleOrTransform;
- (void)translateChildrenFrameToLayers:(id)arg1;
- (id)moveLayersToParent;
- (void)ungroupSingleChildDescendentGroups;
- (id)ungroup;
- (void)setUpNewGroup;
- (void)insertLayers:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertLayers:(id)arg1 afterLayer:(id)arg2;
- (void)insertLayers:(id)arg1 beforeLayer:(id)arg2;
- (BOOL)enumerateLayersWithOptions:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)enumerateLayers:(CDUnknownBlockType)arg1;
- (unsigned long long)indexOfLayer:(id)arg1;
- (id)layerAtIndex:(unsigned long long)arg1;
- (id)lastLayer;
- (id)firstLayer;
- (BOOL)containsMultipleLayers;
- (BOOL)containsOneLayer;
- (BOOL)containsLayers;
- (BOOL)containsNoOrOneLayers;
- (BOOL)canContainLayer:(id)arg1;
- (unsigned long long)containedLayersCount;
- (id)containedLayers;
- (id)CSSAttributeString;

// Remaining properties
@property(readonly, nonatomic) NSArray *layers;

@end

