//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSContentDrawView, MSLayerArray, MSLayerMeasurementTarget, NSNumberFormatter;

@interface MSLayerMeasurementRenderer : NSObject
{
    BOOL _isEnabled;
    MSLayerArray *_selectedLayers;
    MSLayerMeasurementTarget *_measurementTarget;
    unsigned long long _measurementOptions;
    NSNumberFormatter *_numberFormatter;
    MSContentDrawView *_view;
}

@property(nonatomic) __weak MSContentDrawView *view; // @synthesize view=_view;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(nonatomic) unsigned long long measurementOptions; // @synthesize measurementOptions=_measurementOptions;
@property(retain, nonatomic) MSLayerMeasurementTarget *measurementTarget; // @synthesize measurementTarget=_measurementTarget;
@property(retain, nonatomic) MSLayerArray *selectedLayers; // @synthesize selectedLayers=_selectedLayers;
@property(nonatomic) BOOL isEnabled; // @synthesize isEnabled=_isEnabled;
- (void).cxx_destruct;
- (BOOL)isMeasuringDistance;
- (void)clear;
- (void)drawDistanceFromRect:(struct CGRect)arg1 toLargerRect:(struct CGRect)arg2 zoomScale:(double)arg3;
- (void)drawDashLinesBetweenRect:(struct CGRect)arg1 andRect:(struct CGRect)arg2 zoomScale:(double)arg3;
- (void)drawDistanceFromRect:(struct CGRect)arg1 toRect:(struct CGRect)arg2 zoomScale:(double)arg3;
- (void)drawDistanceFromRect:(struct CGRect)arg1 toGuides:(id)arg2 zoomScale:(double)arg3;
- (void)prepareForGeometryChange;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (struct CGRect)rectForPositionDrawingForLayers:(id)arg1;
- (void)drawOutlineForRect:(struct CGRect)arg1 zoomScale:(double)arg2;
- (void)drawWithZoomScale:(double)arg1;
- (struct CGRect)drawingRectForData:(id)arg1;
- (id)measurementData;

@end

