//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSDocumentAction.h"

@class NSString;

@interface MSListTypeAction : MSDocumentAction
{
    NSString *_marker;
}

@property(readonly, nonatomic) NSString *marker; // @synthesize marker=_marker;
- (void).cxx_destruct;
- (BOOL)validateMenuItem:(id)arg1;
- (id)selectedListMarkers;
- (BOOL)isActive;
- (void)doPerformAction:(id)arg1;
- (BOOL)validate;

@end

