//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SketchControllers/MSAction.h>

#import "MSWindowBadgeAction-Protocol.h"

@class NSAttributedString, NSColor, NSString;

@interface MSLibraryUpdatesAvailableBadgeAction : MSAction <MSWindowBadgeAction>
{
}

- (id)librariesWithUpdates;
@property(readonly, nonatomic) NSColor *badgeTint;
@property(readonly, nonatomic) unsigned long long numberOfBadges;
- (id)label;
- (void)doPerformAction:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSAttributedString *badgeTitle; // @dynamic badgeTitle;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

