//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSManageSharedObjectBaseViewController.h"

@interface MSManageTextStyleView : MSManageSharedObjectBaseViewController
{
}

- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)removeSharedObject:(id)arg1;
- (id)sharedObjectsSortedByName;

@end

