//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSEventHandler.h"

@interface MSMakeGridEventHandler : MSEventHandler
{
    // Error parsing type: , name: gridConstructor
    // Error parsing type: , name: selectionOverlayController
    // Error parsing type: , name: $__lazy_storage_$_inspectorViewController
    // Error parsing type: , name: _ignoreChangesCount
}

- (void).cxx_destruct;
- (id)init;
- (void)documentDidChange:(id)arg1;
- (id)inspectorViewControllersForLayers:(id)arg1 standardControllers:(id)arg2;
@property(nonatomic, readonly) unsigned long long inspectorLocation;
- (void)handlerWillLoseFocus;
- (void)handlerGotFocus;
- (id)initWithCoder:(id)arg1;
- (id)initWithManager:(id)arg1;

@end

