//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MTLDepthStencilState, MTLLibrary, MTLRenderPipelineState;

@interface MSMetalRenderPipeline : NSObject
{
    BOOL _useDepthStencil;
    id <MTLLibrary> _library;
    id <MTLRenderPipelineState> _pipelineState;
    id <MTLDepthStencilState> _depthStencilState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <MTLDepthStencilState> depthStencilState; // @synthesize depthStencilState=_depthStencilState;
@property(readonly, nonatomic) BOOL useDepthStencil; // @synthesize useDepthStencil=_useDepthStencil;
@property(readonly, nonatomic) id <MTLRenderPipelineState> pipelineState; // @synthesize pipelineState=_pipelineState;
@property(readonly, nonatomic) id <MTLLibrary> library; // @synthesize library=_library;
- (id)fragmentFunctionName;
- (id)vertexFunctionName;
- (id)vertexDescriptor;
- (id)createPipelineState:(unsigned long long)arg1 depthStencilFormat:(unsigned long long)arg2;
- (id)pipelineStateDescriptor:(unsigned long long)arg1 depthStencilFormat:(unsigned long long)arg2;
- (id)depthStencilDescriptor;
- (id)initWithLibrary:(id)arg1 pixelFormat:(unsigned long long)arg2 depthStencilFormat:(unsigned long long)arg3;
- (id)initWithLibrary:(id)arg1 pixelFormat:(unsigned long long)arg2;

@end

