//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "MSClickableTextFieldDelegate.h"

@class MSClickableTextField, NSString;

@interface MSMirrorIntroViewController : NSViewController <MSClickableTextFieldDelegate>
{
    MSClickableTextField *_downloadField;
}

@property(retain, nonatomic) MSClickableTextField *downloadField; // @synthesize downloadField=_downloadField;
- (void).cxx_destruct;
- (void)textFieldDidClick:(id)arg1;
- (BOOL)textFieldCanBeClicked:(id)arg1;
- (void)downloadMirror:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (struct CGSize)preferredContentSize;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

