//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSModelObject.h"

#import "MSModelBase.h"

@class MSDocumentData, NSObject<NSCopying><NSCoding>, NSString;

@interface MSModelBase : MSModelObject <MSModelBase>
{
    id _cachedImmutableModelObject;
    MSModelBase *_parentObject;
    MSDocumentData *_documentData;
}

+ (void)performWithoutUpdateEvents:(CDUnknownBlockType)arg1;
+ (Class)immutableClass;
@property(nonatomic) __weak MSDocumentData *documentData; // @synthesize documentData=_documentData;
- (void).cxx_destruct;
- (id)undoManager;
- (void)setUndoActionSenderAndName:(id)arg1;
- (void)setUndoActionName:(id)arg1;
- (BOOL)isUndoing;
- (void)registerUndoNamed:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)syncPropertiesMatchingReference:(id)arg1 withObject:(id)arg2;
- (void)breakConnectionWith:(id)arg1;
@property(nonatomic) __weak MSModelBase *parentObject; // @synthesize parentObject=_parentObject;
- (id)parentGroupRecursive;
- (id)parentGroup;
- (void)setAsParentOnChildren;
- (id)rootModelObject;
- (void)invalidateCachedImmutableModelObjects;
@property(readonly, nonatomic) id immutableModelObject;
- (id)copyIncludingObjectIDS;
- (void)prepareCopy:(id)arg1;
- (void)prepareObjectCopy:(id)arg1;
- (id)copyEmpty;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithImmutableModelObject:(id)arg1;
- (id)init;
- (void)performPostChangeTasksAndGenerateUpdates:(BOOL)arg1;
- (void)objectDidChange;
@property(retain, nonatomic) id cachedImmutableModelObject;
- (void)performInitWithImmutableModelObject:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSObject<NSCopying><NSCoding> *objectID;
@property(readonly) Class superclass;

@end

