//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSNetworkHelper : NSObject
{
}

+ (id)currentIPv4Address;
+ (id)currentSubnet;
+ (BOOL)isValidIPWithPort:(id)arg1;
+ (BOOL)isValidIP:(id)arg1;

@end

