//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@interface MSNestedScrollView : NSScrollView
{
}

- (long long)scrollerStyle;
- (void)setScrollerStyle:(long long)arg1;
- (void)scrollWheel:(id)arg1;
- (void)updateDocumentView;
- (void)viewDidMoveToWindow;
- (void)dealloc;

@end

