//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSNormalBaseEventHandler.h"

@class MSNormalEventHandler, MSShapePathLayer, _TtC6Sketch16MSLineResizeTool;

@interface MSNormalResizeLineEventHandler : MSNormalBaseEventHandler
{
    MSShapePathLayer *_layer;
    long long _pointIndex;
    MSNormalEventHandler *_normalEventHandler;
    _TtC6Sketch16MSLineResizeTool *_tool;
}

@property(readonly, nonatomic) _TtC6Sketch16MSLineResizeTool *tool; // @synthesize tool=_tool;
@property(retain, nonatomic) MSNormalEventHandler *normalEventHandler; // @synthesize normalEventHandler=_normalEventHandler;
@property(nonatomic) long long pointIndex; // @synthesize pointIndex=_pointIndex;
@property(retain, nonatomic) MSShapePathLayer *layer; // @synthesize layer=_layer;
- (void).cxx_destruct;
- (id)cursorForRadians:(double)arg1;
- (BOOL)updateCursor;
- (void)updateVisibleHandle;
- (BOOL)absoluteMouseUp:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)absoluteMouseDragged:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (BOOL)absoluteMouseDown:(struct CGPoint)arg1 clickCount:(unsigned long long)arg2 flags:(unsigned long long)arg3;
- (void)handlerWillLoseFocus;
- (id)initWithManager:(id)arg1;

@end

