//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSNormalEventData : NSObject
{
    BOOL _hasMultipleTouches;
    BOOL _didMouseDown;
    struct CGPoint _mouseDown;
    struct CGPoint _midPoint;
    struct CGPoint _originalScrollOrigin;
}

@property(nonatomic) struct CGPoint originalScrollOrigin; // @synthesize originalScrollOrigin=_originalScrollOrigin;
@property(nonatomic) struct CGPoint midPoint; // @synthesize midPoint=_midPoint;
@property(nonatomic) struct CGPoint mouseDown; // @synthesize mouseDown=_mouseDown;
@property(nonatomic) BOOL didMouseDown; // @synthesize didMouseDown=_didMouseDown;
@property(nonatomic) BOOL hasMultipleTouches; // @synthesize hasMultipleTouches=_hasMultipleTouches;

@end

