//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "MSInspectorChildController.h"
#import "MSStylePartInspectorDelegate.h"

@class MSBlurInspectorViewController, MSColorControlsInspectorViewController, MSEventHandler, MSExportInspectorViewController, MSInspectorStackView, MSLayerInspectorViewController, MSMultipleBorderInspectorViewController, MSMultipleFillInspectorViewController, MSMultipleShadowInspectorViewController, MSReflectionInspectorViewController, NSArray, NSScrollView, NSString;

@interface MSNormalInspector : NSViewController <MSStylePartInspectorDelegate, MSInspectorChildController>
{
    MSLayerInspectorViewController *layerViewController;
    MSMultipleShadowInspectorViewController *shadowViewController;
    MSMultipleShadowInspectorViewController *innerShadowViewController;
    MSMultipleBorderInspectorViewController *borderViewController;
    MSBlurInspectorViewController *blurViewController;
    MSColorControlsInspectorViewController *colorControlsViewController;
    MSReflectionInspectorViewController *reflectionViewController;
    MSMultipleFillInspectorViewController *fillViewController;
    MSExportInspectorViewController *exportViewController;
    MSInspectorStackView *_stackView;
    NSArray *_layers;
    MSEventHandler *_eventHandler;
    NSScrollView *_scrollView;
}

@property(retain, nonatomic) NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) MSEventHandler *eventHandler; // @synthesize eventHandler=_eventHandler;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
@property(retain, nonatomic) MSInspectorStackView *stackView; // @synthesize stackView=_stackView;
- (void).cxx_destruct;
- (void)adjustInspectorToColorPopover:(id)arg1 sender:(id)arg2;
- (id)views;
- (BOOL)shouldHideExportBar;
- (void)showBorderOptionsAction:(id)arg1;
- (void)showFillOptionsAction:(id)arg1;
- (id)sharedObjectsSection;
- (void)changeTextLayerFont:(id)arg1;
- (void)colorMagnifierAction:(id)arg1;
- (void)returnToDefaultHandler;
- (id)viewControllers;
- (void)changeColor:(id)arg1;
- (void)layerPositionPossiblyChanged;
- (void)prepareViewControllers;
- (void)reloadInspectorStack:(id)arg1;
- (void)prepareForDisplay;
- (void)openPopoverForStylePart:(unsigned long long)arg1 atIndex:(unsigned long long)arg2;
- (void)selectionDidChangeTo:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

