//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSOpenInLibraryAction.h"

@class MSShareableObjectReference;

@interface MSOpenSwatchInLibraryAction : MSOpenInLibraryAction
{
    MSShareableObjectReference *_swatchReference;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MSShareableObjectReference *swatchReference; // @synthesize swatchReference=_swatchReference;
- (id)label;
- (void)openLibraryForColors:(id)arg1;
- (long long)validationStatus;
- (id)foreignObjects;

@end

