//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MSAvailableOverride, NSArray, NSSet;

@interface MSOverrideViewController : NSViewController
{
    MSAvailableOverride *_primaryOverride;
    NSArray *_instances;
    NSSet *_allOverrides;
}

@property(retain, nonatomic) NSSet *allOverrides; // @synthesize allOverrides=_allOverrides;
@property(retain, nonatomic) NSArray *instances; // @synthesize instances=_instances;
@property(readonly, nonatomic) MSAvailableOverride *primaryOverride; // @synthesize primaryOverride=_primaryOverride;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL hasSingleOverride;
- (void)applyOverrideToSelectedLayers:(id)arg1;
- (void)overrideValueAction:(id)arg1;
- (id)labelView;
- (id)valueFromControlView:(id)arg1;
- (id)controlViewForEditingOverride;
- (BOOL)hasStandardCellHeight;
- (void)build;
- (id)views;
- (id)initWithPrimaryOverride:(id)arg1;

@end

