//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSSymbolMaster, NSMutableArray;

@interface MSOverrideManagementController : NSObject
{
    MSSymbolMaster *_master;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) MSSymbolMaster *master; // @synthesize master=_master;
- (void).cxx_destruct;
- (BOOL)isOverridePoint:(id)arg1 configurableIn:(id)arg2;

@end

