//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchControllers/MSOverrideManagementItem.h>

@class NSImage, NSString;

@interface MSOverrideManagementPropertyTitle : MSOverrideManagementItem
{
}

@property(readonly, nonatomic) NSImage *previewIcon;
- (id)description;
@property(readonly, nonatomic) NSString *title;
- (id)initWithAvailableOverride:(id)arg1 onMaster:(id)arg2;

@end

