//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSPasteboardTextWriting : NSObject
{
}

+ (BOOL)writeAttributedString:(id)arg1 toPasteboard:(id)arg2 type:(id)arg3 documentColorSpace:(id)arg4;
+ (id)supportedTypes;

@end

