//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSPointSnapperWorkings;

@interface MSPointSnapper : NSObject
{
    BOOL _rulersVisible;
    double _snapThreshold;
    unsigned long long _allowedAxes;
    id <MSBasicDelegate> _rulerProvider;
    MSPointSnapperWorkings *_xWorkings;
    MSPointSnapperWorkings *_yWorkings;
}

@property(readonly, nonatomic) MSPointSnapperWorkings *yWorkings; // @synthesize yWorkings=_yWorkings;
@property(readonly, nonatomic) MSPointSnapperWorkings *xWorkings; // @synthesize xWorkings=_xWorkings;
@property(retain, nonatomic) id <MSBasicDelegate> rulerProvider; // @synthesize rulerProvider=_rulerProvider;
@property(nonatomic) BOOL rulersVisible; // @synthesize rulersVisible=_rulersVisible;
@property(nonatomic) unsigned long long allowedAxes; // @synthesize allowedAxes=_allowedAxes;
@property(nonatomic) double snapThreshold; // @synthesize snapThreshold=_snapThreshold;
- (void).cxx_destruct;
- (void)trySnapToHandleAtIndexPath:(id)arg1 location:(struct CGPoint)arg2 shape:(id)arg3 layer:(id)arg4 selection:(id)arg5;
- (void)trySnapToMidpointOfLayer:(id)arg1 geometryLayer:(id)arg2;
- (id)snapPoint:(struct CGPoint)arg1 inLayer:(id)arg2 toShapePathLayers:(id)arg3 indexPathsForSelectedHandles:(id)arg4;
- (id)init;

@end

