//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSharedObjectAction.h"

@interface MSReplaceWithSymbolAction : MSSharedObjectAction
{
}

- (BOOL)showInToolbar;
- (void)replaceLayer:(id)arg1 withSymbol:(id)arg2;
- (void)doPerformAction:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)validate;
- (id)unsortedSharedObjects;
- (id)sharedObjectName;
- (id)initWithDocument:(id)arg1;

@end

