//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSOverrideAction.h"

#import "MSReplaceOverride-Protocol.h"

@class MSForeignObjectMenuBuilder, NSString;

@interface MSReplaceOverrideStyleAction : MSOverrideAction <MSReplaceOverride>
{
    MSForeignObjectMenuBuilder *_layerStyleMenuBuilder;
    MSForeignObjectMenuBuilder *_textStyleMenuBuilder;
}

- (void).cxx_destruct;
- (void)applyStyleOverride:(id)arg1 styleReference:(id)arg2;
- (void)replaceOverrideWithStyleAction:(id)arg1;
- (void)buildMenu:(id)arg1;
@property(readonly, nonatomic) MSForeignObjectMenuBuilder *textStyleMenuBuilder; // @synthesize textStyleMenuBuilder=_textStyleMenuBuilder;
@property(readonly, nonatomic) MSForeignObjectMenuBuilder *layerStyleMenuBuilder; // @synthesize layerStyleMenuBuilder=_layerStyleMenuBuilder;
@property(readonly, nonatomic) MSForeignObjectMenuBuilder *menuBuilder;
- (BOOL)validateMenuItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

