//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSharedSymbolAction.h"

@interface MSReplaceWithSymbolRootAction : MSSharedSymbolAction
{
}

- (BOOL)validateMenuItem:(id)arg1;
- (long long)validationStatus;
- (void)replaceWithSymbolRoot:(id)arg1;

@end

