//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSNormalBaseEventHandler.h"

#import "NSTouchBarDelegate.h"

@class MSDragGestureRecognizer, NSString;

@interface MSRotateEventHandler : MSNormalBaseEventHandler <NSTouchBarDelegate>
{
    long long _startingDegrees;
    double _startingRotation;
    struct CGPoint _previousMouseLocation;
    BOOL _exitOnMouseUp;
    BOOL _disableMoving;
    BOOL _showMeasurementLabel;
    MSDragGestureRecognizer *_dragGestureRecognizer;
    unsigned long long _draggedComponent;
    struct CGPoint _rotationCenter;
}

+ (id)cursorForDegrees:(long long)arg1;
+ (long long)degreesForPoint:(struct CGPoint)arg1 inLayer:(id)arg2 rotationCenter:(struct CGPoint)arg3;
@property(nonatomic) unsigned long long draggedComponent; // @synthesize draggedComponent=_draggedComponent;
@property(readonly, nonatomic) MSDragGestureRecognizer *dragGestureRecognizer; // @synthesize dragGestureRecognizer=_dragGestureRecognizer;
@property(nonatomic) BOOL showMeasurementLabel; // @synthesize showMeasurementLabel=_showMeasurementLabel;
@property(nonatomic) struct CGPoint rotationCenter; // @synthesize rotationCenter=_rotationCenter;
@property(nonatomic) BOOL disableMoving; // @synthesize disableMoving=_disableMoving;
@property(nonatomic) BOOL exitOnMouseUp; // @synthesize exitOnMouseUp=_exitOnMouseUp;
- (void).cxx_destruct;
- (void)refreshTouchBarItemWithIdentifier:(id)arg1;
- (void)rotationBarAction:(id)arg1;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)makeTouchBar;
- (void)drawRotationMeasurementLabel;
- (void)drawRotationCenter;
- (void)drawInRect:(struct CGRect)arg1 cache:(id)arg2;
- (double)alignDegreesTo45Angles:(double)arg1;
- (long long)degreesForPoint:(struct CGPoint)arg1;
- (void)keyDown:(id)arg1;
- (BOOL)absoluteMouseUp:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (void)mouseDraggedRotateLayer:(id)arg1 mouse:(struct CGPoint)arg2 flags:(unsigned long long)arg3;
- (void)mouseDraggedMoveLayer:(id)arg1 mouse:(struct CGPoint)arg2;
- (BOOL)mouseDraggedEvent:(id)arg1;
- (BOOL)absoluteMouseDown:(struct CGPoint)arg1 clickCount:(unsigned long long)arg2 flags:(unsigned long long)arg3;
- (BOOL)absoluteMouseMoved:(struct CGPoint)arg1 flags:(unsigned long long)arg2;
- (void)handleDrag:(id)arg1;
- (unsigned long long)componentAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)rotationCenterInAbsoluteCoordinates;
- (void)handlerWillLoseFocus;
- (void)handlerGotFocus;
- (id)initWithManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

