//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSScaleEventHandler.h"

#import "_TtP6Sketch24SelectionOverlayDelegate_-Protocol.h"

@interface MSScaleEventHandler (Sketch) <_TtP6Sketch24SelectionOverlayDelegate_>
- (id)collectionOverlay:(id)arg1 overlayItemContainerForSupplementaryElementOfKind:(id)arg2 layoutAttributes:(id)arg3 parameters:(struct MSRenderingParameters)arg4;
- (id)collectionOverlay:(id)arg1 overlayItemContainerForItemAtIndexPath:(id)arg2 layoutAttributes:(id)arg3 parameters:(struct MSRenderingParameters)arg4;
- (id)collectionOverlay:(id)arg1 overlayItemImagesForColorSpace:(struct CGColorSpace *)arg2 backingScale:(double)arg3;
- (long long)collectionOverlay:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)selectionOverlayWithDidFinishAdjustingHandle:(id)arg1;
- (void)selectionOverlay:(id)arg1 adjustHandleOfKind:(id)arg2 at:(id)arg3 to:(struct CGPoint)arg4 modifierFlags:(unsigned long long)arg5;
- (void)selectionOverlay:(id)arg1 willBeginAdjustingHandleOfKind:(id)arg2 at:(id)arg3 location:(struct CGPoint)arg4 modifierFlags:(unsigned long long)arg5;
- (id)selectionOverlay:(id)arg1 cursorForHandleOfKind:(id)arg2 at:(id)arg3 location:(struct CGPoint)arg4 modifierFlags:(unsigned long long)arg5;
- (BOOL)selectionOverlay:(id)arg1 selectItemAt:(struct CGPoint)arg2 modifierFlags:(unsigned long long)arg3;
- (struct CGSize)selectionOverlay:(id)arg1 layout:(id)arg2 sizeForHandleOfKind:(id)arg3 atIndexPath:(id)arg4;
- (struct CGRect)selectionOverlay:(id)arg1 layout:(id)arg2 frameForItemAt:(id)arg3;
@end

