//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSSelectionOverlayController.h"

#import "_TtP6Sketch25SelectionRendererDelegate_-Protocol.h"

@interface MSSelectionOverlayController (Sketch2) <_TtP6Sketch25SelectionRendererDelegate_>
- (void)spacingRendererWithDidFinishAdjusting:(id)arg1;
- (void)spacingRenderer:(id)arg1 willBeginAdjustingSpaceAt:(id)arg2;
- (void)spacingRenderer:(id)arg1 adjustSpacingAt:(id)arg2 to:(struct CGPoint)arg3 modifierFlags:(unsigned long long)arg4;
- (void)collectionRenderer:(id)arg1 trackedMouse:(struct CGPoint)arg2;
- (id)collectionRenderer:(id)arg1 cursorForResizeHandleOfKind:(id)arg2 at:(struct CGPoint)arg3 modifierFlags:(unsigned long long)arg4;
- (long long)collectionRenderer:(id)arg1 dotRectTypeForItemAt:(id)arg2;
@end

