//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface MSSeparatorConfigurableView : NSView
{
    BOOL _wantsSeparator;
    BOOL _inset;
}

@property(nonatomic) BOOL inset; // @synthesize inset=_inset;
@property(nonatomic) BOOL wantsSeparator; // @synthesize wantsSeparator=_wantsSeparator;
- (BOOL)wantsSeparatorBetweenSelfAndView:(id)arg1;
- (struct NSEdgeInsets)separatorInsetBetweenSelfAndView:(id)arg1;

@end

