//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSharedStyle.h"

#import "MSSharedStyle.h"

@class MSStyle, NSObject<NSCopying><NSCoding>, NSString;

@interface MSSharedStyle : _MSSharedStyle <MSSharedStyle>
{
}

- (unsigned long long)type;
- (id)newInstance;
@property(readonly, nonatomic) MSStyle *style;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSObject<NSCopying><NSCoding> *objectID;
@property(readonly) Class superclass;
@property(readonly, nonatomic) id <MSModelObjectCommon> valueGeneric;

@end

