//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSAction.h"

@interface MSShowSupportPageAction : MSAction
{
}

- (void)doPerformAction:(id)arg1;
- (void)showSupportPage:(id)arg1;

@end

