//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSharedStyleContainer.h"

#import "MSSharedStyleContainer.h"

@class NSObject<NSCopying><NSCoding>, NSString;

@interface MSSharedStyleContainer : _MSSharedStyleContainer <MSSharedStyleContainer>
{
}

- (void)registerInstance:(id)arg1 withSharedStyle:(id)arg2;
- (unsigned long long)numberOfSharedStyles;
- (long long)indexOfSharedStyle:(id)arg1;
- (id)sharedStyleAtIndex:(unsigned long long)arg1;
- (id)sharedStyleWithID:(id)arg1;
- (id)sharedStyleForInstance:(id)arg1;
- (BOOL)isSharedStyleForInstance:(id)arg1;
- (void)removeSharedStyle:(id)arg1;
- (id)mergeSharedStyleWithName:(id)arg1 sharedStyleID:(id)arg2 instance:(id)arg3;
- (id)addSharedStyleWithName:(id)arg1 firstInstance:(id)arg2;
- (void)enumeratePotentialInstancesInContainer:(id)arg1 block:(CDUnknownBlockType)arg2;
- (unsigned long long)validStyleType;
- (Class)sharedObjectClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSObject<NSCopying><NSCoding> *objectID;
@property(readonly, nonatomic) id <MSArray> objectsGeneric;
@property(readonly) Class superclass;

@end

