//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class MSShareableObjectReference, MSSharedStylesPopUpButtonCell, NSImage;

@protocol MSSharedStylesPopUpButtonCellDelegate
- (NSImage *)cachedImageForPopupButtonCell:(MSSharedStylesPopUpButtonCell *)arg1 withSharedObject:(MSShareableObjectReference *)arg2;
- (void)popupButtonCell:(MSSharedStylesPopUpButtonCell *)arg1 didCreatePreviewImage:(NSImage *)arg2 forSharedObject:(MSShareableObjectReference *)arg3;
@end

