//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MSDocumentData, MSLayer, MSSidebarListController, NSArray, NSColorSpace;

@protocol MSSidebarControllerDelegate <NSObject>
@property(readonly, nonatomic) NSColorSpace *colorSpace;
@property(readonly, nonatomic) MSDocumentData *documentData;
- (void)sidebarController:(MSSidebarListController *)arg1 hoveredLayerDidChangeTo:(MSLayer *)arg2;
- (NSArray *)sidebarControllerContextMenuItemsForCurrentSelection:(MSSidebarListController *)arg1;
- (void)sidebarController:(MSSidebarListController *)arg1 validateRemovalOfPages:(NSArray *)arg2 withRemovalBlock:(void (^)(void))arg3;
- (void)sidebarController:(MSSidebarListController *)arg1 didChangeSelection:(NSArray *)arg2;
- (void)sidebarControllerDidUpdate:(MSSidebarListController *)arg1;
@end

