//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSDocumentData;
@protocol MSSidebarControllerDelegate;

@interface MSSidebarListController : NSObject
{
    id <MSSidebarControllerDelegate> _delegate;
    id _rootObject;
}

@property(readonly, nonatomic) id rootObject; // @synthesize rootObject=_rootObject;
@property(nonatomic) __weak id <MSSidebarControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)dataController:(id)arg1 exportNodes:(id)arg2 toFolder:(id)arg3;
- (struct CGPoint)originalPositionOfLayersInPasteboard:(id)arg1 forNewParent:(id)arg2;
- (BOOL)dataController:(id)arg1 copyFromPasteboard:(id)arg2 toParent:(id)arg3 after:(id)arg4;
- (BOOL)dataController:(id)arg1 moveFromPasteboard:(id)arg2 toParent:(id)arg3 after:(id)arg4;
- (BOOL)moveNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)dataController:(id)arg1 canCopyFromPasteboard:(id)arg2 toParent:(id)arg3 after:(id)arg4;
- (BOOL)canCopyNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (BOOL)dataController:(id)arg1 canMoveFromPasteboard:(id)arg2 toParent:(id)arg3 after:(id)arg4;
- (BOOL)canMoveNode:(id)arg1 toParent:(id)arg2 after:(id)arg3;
- (id)dragTypesForDataController:(id)arg1;
- (id)readDragNodesFromPasteboard:(id)arg1;
- (BOOL)dataController:(id)arg1 writeNodes:(id)arg2 toPasteboard:(id)arg3;
@property(readonly, nonatomic) Class pasteboardWriterClass;
- (id)layersFromNodeArray:(id)arg1;
- (id)layerForNode:(id)arg1;
@property(readonly, nonatomic) __weak MSDocumentData *documentData;
- (id)initWithDelegate:(id)arg1;

@end

