//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSBlurInspectorViewController, MSColorControlsInspectorViewController, MSLayerInspectorViewController, MSMultipleBorderInspectorViewController, MSMultipleFillInspectorViewController, MSMultipleShadowInspectorViewController, MSReflectionInspectorViewController;

@interface MSStandardInspectorViewControllers : NSObject
{
    MSLayerInspectorViewController *_layerViewController;
    MSMultipleFillInspectorViewController *_fillViewController;
    MSMultipleBorderInspectorViewController *_borderViewController;
    MSBlurInspectorViewController *_blurViewController;
    MSColorControlsInspectorViewController *_colorControlsViewController;
    MSMultipleShadowInspectorViewController *_shadowViewController;
    MSMultipleShadowInspectorViewController *_innerShadowViewController;
    MSReflectionInspectorViewController *_reflectionViewController;
}

@property(readonly, nonatomic) MSReflectionInspectorViewController *reflectionViewController; // @synthesize reflectionViewController=_reflectionViewController;
@property(readonly, nonatomic) MSMultipleShadowInspectorViewController *innerShadowViewController; // @synthesize innerShadowViewController=_innerShadowViewController;
@property(readonly, nonatomic) MSMultipleShadowInspectorViewController *shadowViewController; // @synthesize shadowViewController=_shadowViewController;
@property(readonly, nonatomic) MSColorControlsInspectorViewController *colorControlsViewController; // @synthesize colorControlsViewController=_colorControlsViewController;
@property(readonly, nonatomic) MSBlurInspectorViewController *blurViewController; // @synthesize blurViewController=_blurViewController;
@property(readonly, nonatomic) MSMultipleBorderInspectorViewController *borderViewController; // @synthesize borderViewController=_borderViewController;
@property(readonly, nonatomic) MSMultipleFillInspectorViewController *fillViewController; // @synthesize fillViewController=_fillViewController;
@property(readonly, nonatomic) MSLayerInspectorViewController *layerViewController; // @synthesize layerViewController=_layerViewController;
- (void).cxx_destruct;
- (id)init;

@end

