//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@protocol MSStackViewScrollViewDelegate;

@interface MSStackViewScrollView : NSScrollView
{
    id <MSStackViewScrollViewDelegate> _delegate;
}

@property(nonatomic) __weak id <MSStackViewScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setScrollerStyle:(long long)arg1;
- (void)reflectScrolledClipView:(id)arg1;
- (id)enclosedStackView;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

