//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStyleBorder.h"

#import "MSStyleBorder.h"

@class NSObject<NSCopying><NSCoding>, NSString;

@interface MSStyleBorder : _MSStyleBorder <MSStyleBorder>
{
}

+ (id)defaultFillColor;
- (BOOL)supportsAdvancedBorderSettings;
- (void)multiplyBy:(double)arg1;
- (long long)patternFillType;
- (double)noiseIntensity;
- (void)performInitEmptyObject;
- (id)topViewForColorInspector:(id)arg1;
- (id)blendingViewForColorInspector:(id)arg1;
- (id)CSSAttributeString;

// Remaining properties
@property(readonly, nonatomic) id <MSColor> colorGeneric;
@property(readonly, nonatomic) id <MSGraphicsContextSettings> contextSettingsGeneric;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) unsigned long long fillType;
@property(readonly, nonatomic) id <MSGradient> gradientGeneric;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BOOL isEnabled;
@property(readonly, copy, nonatomic) NSObject<NSCopying><NSCoding> *objectID;
@property(readonly, nonatomic) long long position;
@property(readonly) Class superclass;
@property(readonly, nonatomic) double thickness;

@end

