//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SketchControllers/MSLayoutElement.h>

@interface MSStack : MSLayoutElement
{
    // Error parsing type: , name: axis
    // Error parsing type: , name: spacing
}

@property(nonatomic) double spacing; // @synthesize spacing;

@end

