//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSStylePartInspectorItem.h"

#import "MSInspectorSection-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class NSString, NSView;
@protocol MSInspectorSectionDelegate;

@interface MSStylePartInspectorViewController : MSStylePartInspectorItem <MSInspectorSection, NSWindowDelegate>
{
    NSView *nameView;
    id <MSInspectorSectionDelegate> _delegate;
    unsigned long long _index;
}

+ (id)reusableControllerArray;
+ (id)stylePartViewController;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(nonatomic) __weak id <MSInspectorSectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)updateDisplayedValues;
- (void)closePopoverImmediately:(BOOL)arg1;
- (id)views;
- (void)didGetAddedToInspector;
- (BOOL)hasEnabledStyle;
- (void)prepare;
- (void)awakeFromNib;
- (void)prepareForReuse;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

