//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSStyleBlur.h"

#import "MSStyleBlur.h"

@class NSObject<NSCopying><NSCoding>, NSString;

@interface MSStyleBlur : _MSStyleBlur <MSStyleBlur>
{
}

- (void)multiplyBy:(double)arg1;
- (double)cropRadius;

// Remaining properties
@property(readonly, nonatomic) struct CGPoint center;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BOOL isEnabled;
@property(readonly, nonatomic) double motionAngle;
@property(readonly, copy, nonatomic) NSObject<NSCopying><NSCoding> *objectID;
@property(readonly, nonatomic) double radius;
@property(readonly) Class superclass;
@property(readonly, nonatomic) unsigned long long type;

@end

