//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSSVGBlendMode : NSObject
{
}

+ (id)svgFromSketchBlendMode:(long long)arg1;
+ (long long)sketchBlendModeFromSVG:(id)arg1;
+ (void)initialize;

@end

