//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSymbolMaster.h"

#import "BCSortable-Protocol.h"
#import "MSLayerPreviewability-Protocol.h"
#import "MSPreviewGeneration-Protocol.h"
#import "MSSharedObjectStyling-Protocol.h"

@class NSArray, NSSet, NSString;

@interface MSSymbolMaster : _MSSymbolMaster <MSPreviewGeneration, MSLayerPreviewability, MSSharedObjectStyling, BCSortable>
{
    BOOL _isDirty;
    long long _changeIdentifier;
}

+ (void)copyPropertiesFrom:(id)arg1 to:(id)arg2;
+ (id)convertSymbolToArtboard:(id)arg1;
+ (id)convertArtboardToSymbol:(id)arg1;
@property(nonatomic) BOOL isDirty; // @synthesize isDirty=_isDirty;
@property(nonatomic) long long changeIdentifier; // @synthesize changeIdentifier=_changeIdentifier;
- (BOOL)limitsSelectionToBounds;
- (void)object:(id)arg1 didChangeProperty:(id)arg2;
- (id)parentSymbol;
- (id)rootForNameUniquing;
- (id)ancestorIDsForLayerNamed:(id)arg1 skip:(id)arg2;
- (id)ancestorIDsForLayerNamed:(id)arg1;
- (BOOL)isSafeToDelete;
- (void)multiplyBy:(double)arg1;
- (id)ungroup;
- (void)removeFromParentAndDetachAllInstances;
- (void)detachAllInstances;
- (BOOL)ensureSymbolIDUniqueInDocument:(id)arg1;
- (BOOL)canInsertInstanceIntoGroupWithoutInfiniteRecursion:(id)arg1;
- (BOOL)hasInstances;
@property(readonly, nonatomic) NSArray *allInfluencedInstances;
- (id)nestedSymbolsSkipping:(id)arg1;
@property(readonly, nonatomic) NSSet *nestedSymbols;
@property(readonly, nonatomic) NSArray *allInstances;
- (id)newSymbolInstance;
- (id)copyWithIDMapping:(id)arg1;
- (void)moveChildrenToIdenticalPositionAfterResizeFromRect:(struct CGRect)arg1;
- (void)copyPropertiesToObject:(id)arg1 options:(unsigned long long)arg2;
- (void)invalidateImmutableObject;
- (void)syncPropertiesFromObject:(id)arg1;
- (void)performInitWithImmutableModelObject:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)generatePreviewWithImageSize:(struct CGSize)arg1 previewSize:(struct CGSize)arg2 colorSpace:(id)arg3 backingScale:(double)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)unselectedPreviewTemplateImage;
- (id)selectedPreviewTemplateImage;
- (struct CGRect)optimalBoundingBox;
- (BOOL)canSnap:(unsigned long long)arg1 toLayer:(id)arg2;
- (Class)shareableObjectReferenceClass_bc;
- (void)applyStyleToMenuItem:(id)arg1 withColorSpace:(id)arg2;
- (void)generatePreviewWithImageSize:(struct CGSize)arg1 previewSize:(struct CGSize)arg2 backingScale:(double)arg3 shadow:(BOOL)arg4 colorSpace:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (void)generatePreviewForSyncSheetWithSize:(struct CGSize)arg1 backingScale:(double)arg2 shadow:(BOOL)arg3 colorSpace:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)generatePreviewForManageSheetWithBackingScale:(double)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)generatePreviewForPopup:(id)arg1 backingScale:(double)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)generatePreviewForMenuItem:(id)arg1 withColorSpace:(id)arg2 backingScale:(double)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (BOOL)previewShouldIndicateSharedStyle;
- (void)applyOverrides:(id)arg1 document:(id)arg2;
@property(readonly, nonatomic) NSArray *availableOverrides;

// Remaining properties
@property(readonly, nonatomic) unsigned long long badgeType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *name;
@property(readonly) Class superclass;

@end

