//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@class MSHangingGlyphView, NSDictionary, NSTimer;

@interface MSTextLayerTextView : NSTextView
{
    MSHangingGlyphView *_hangingGlyphView;
    id <MSTextLayerTextViewDelegate> _textLayerTextViewDelegate;
    NSTimer *_hideSelectionTimer;
    NSDictionary *_selectedTextAttributesBackup;
}

@property(copy, nonatomic) NSDictionary *selectedTextAttributesBackup; // @synthesize selectedTextAttributesBackup=_selectedTextAttributesBackup;
@property(retain, nonatomic) NSTimer *hideSelectionTimer; // @synthesize hideSelectionTimer=_hideSelectionTimer;
@property(nonatomic) __weak id <MSTextLayerTextViewDelegate> textLayerTextViewDelegate; // @synthesize textLayerTextViewDelegate=_textLayerTextViewDelegate;
@property(nonatomic) __weak MSHangingGlyphView *hangingGlyphView; // @synthesize hangingGlyphView=_hangingGlyphView;
- (void).cxx_destruct;
- (id)makeTouchBar;
- (struct CGRect)rectForSelectedRange;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1 avoidAdditionalLayout:(BOOL)arg2;
- (void)selectSimilar:(id)arg1;
- (void)hideSelectionTimerFired:(id)arg1;
- (id)makeHideSelectionTimer;
- (BOOL)writeSelectionToPasteboard:(id)arg1 type:(id)arg2;
- (id)writablePasteboardTypes;
- (void)pasteAttributedString:(id)arg1 replaceRange:(struct _NSRange)arg2 keepStyling:(BOOL)arg3;
- (void)pasteWithOptions:(unsigned long long)arg1;
- (void)pasteWithStyle:(id)arg1;
- (void)paste:(id)arg1;
- (id)readablePasteboardTypes;
- (BOOL)readSelectionFromPasteboard:(id)arg1;
- (void)hideSelectionTemporarily;
- (void)mouseDown:(id)arg1;
- (BOOL)hitTestFromEvent:(id)arg1;
- (void)applyTextListItemColor:(id)arg1;
- (id)applicableTextListItemColor:(SEL)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (void)setTypingAttributes:(id)arg1;
- (void)applyTextColor:(id)arg1 previousTextColors:(id)arg2;
- (BOOL)shouldIgnoreAlreadyApplicableColor:(id)arg1;
- (id)textColorProviderForChangeColorSender:(id)arg1;
- (id)documentColorSpace;
- (id)colorProvidersForRanges:(id)arg1 colorSpace:(id)arg2;
- (void)changeColor:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;

@end

