//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSInspectorItem.h"

#import "MSColorInspectorDelegate-Protocol.h"
#import "MSInspectorMathValueAdaptorDelegate-Protocol.h"
#import "MSNativeColorPanelPresenterDelegate-Protocol.h"
#import "MSStylePartPreviewButtonDelegate-Protocol.h"
#import "NSComboBoxDataSource-Protocol.h"
#import "NSMenuDelegate-Protocol.h"

@class BCPopover, MSImmutableColor, MSInlineUpDownTextField, MSInlineUpDownTextFieldWithMenu, MSInspectorSegmentedControl, MSInspectorValueAdaptor, MSMathInspectorValueAdaptor, MSNativeColorPanelPresenter, MSStylePartPreviewButton, MSTextAttributeEditingContext, MSTextInspectorItemDataSource, NSArrayController, NSButton, NSMenu, NSPopUpButton, NSSegmentedControl, NSSet, NSString, NSTextField, NSView;
@protocol MSTextLayerItemDelegate;

@interface MSTextLayerInspectorItem : MSInspectorItem <MSNativeColorPanelPresenterDelegate, MSInspectorMathValueAdaptorDelegate, NSMenuDelegate, MSColorInspectorDelegate, NSComboBoxDataSource, MSStylePartPreviewButtonDelegate>
{
    NSMenu *_fontSizeMenu;
    MSTextInspectorItemDataSource *_dataSource;
    NSView *_basicView;
    NSButton *_fontFamilyButton;
    NSPopUpButton *_fontWeightPopUpButton;
    MSInlineUpDownTextFieldWithMenu *_fontSizeField;
    MSStylePartPreviewButton *_colorPickerButton;
    MSInlineUpDownTextField *_kerningField;
    MSInlineUpDownTextField *_lineHeightField;
    MSInlineUpDownTextField *_paragraphHeightField;
    MSInspectorSegmentedControl *_alignmentButton;
    NSSegmentedControl *_verticalAlignmentButton;
    NSTextField *_sizingLabel;
    MSInspectorSegmentedControl *_sizingSegmentedControl;
    BCPopover *_popover;
    MSNativeColorPanelPresenter *_colorPanelPresenter;
    NSSet *_fontPostscriptNames;
    MSImmutableColor *_textColor;
    NSArrayController *_layersController;
    MSMathInspectorValueAdaptor *_fontSizeAdaptor;
    MSMathInspectorValueAdaptor *_kerningAdaptor;
    MSMathInspectorValueAdaptor *_paragraphSpacingAdaptor;
    MSInspectorValueAdaptor *_alignmentAdaptor;
    MSMathInspectorValueAdaptor *_lineHeightAdaptor;
    MSInspectorValueAdaptor *_colorAdapor;
    MSTextAttributeEditingContext *_editingContext;
}

+ (void)initialize;
+ (BOOL)canHandleLayer:(id)arg1;
@property(retain, nonatomic) MSTextAttributeEditingContext *editingContext; // @synthesize editingContext=_editingContext;
@property(retain, nonatomic) MSInspectorValueAdaptor *colorAdapor; // @synthesize colorAdapor=_colorAdapor;
@property(retain, nonatomic) MSMathInspectorValueAdaptor *lineHeightAdaptor; // @synthesize lineHeightAdaptor=_lineHeightAdaptor;
@property(retain, nonatomic) MSInspectorValueAdaptor *alignmentAdaptor; // @synthesize alignmentAdaptor=_alignmentAdaptor;
@property(retain, nonatomic) MSMathInspectorValueAdaptor *paragraphSpacingAdaptor; // @synthesize paragraphSpacingAdaptor=_paragraphSpacingAdaptor;
@property(retain, nonatomic) MSMathInspectorValueAdaptor *kerningAdaptor; // @synthesize kerningAdaptor=_kerningAdaptor;
@property(retain, nonatomic) MSMathInspectorValueAdaptor *fontSizeAdaptor; // @synthesize fontSizeAdaptor=_fontSizeAdaptor;
@property(retain, nonatomic) NSArrayController *layersController; // @synthesize layersController=_layersController;
@property(retain, nonatomic) MSImmutableColor *textColor; // @synthesize textColor=_textColor;
@property(copy, nonatomic) NSSet *fontPostscriptNames; // @synthesize fontPostscriptNames=_fontPostscriptNames;
@property(retain, nonatomic) MSNativeColorPanelPresenter *colorPanelPresenter; // @synthesize colorPanelPresenter=_colorPanelPresenter;
@property(retain, nonatomic) BCPopover *popover; // @synthesize popover=_popover;
@property(nonatomic) __weak MSInspectorSegmentedControl *sizingSegmentedControl; // @synthesize sizingSegmentedControl=_sizingSegmentedControl;
@property(retain, nonatomic) NSTextField *sizingLabel; // @synthesize sizingLabel=_sizingLabel;
@property(retain, nonatomic) NSSegmentedControl *verticalAlignmentButton; // @synthesize verticalAlignmentButton=_verticalAlignmentButton;
@property(retain, nonatomic) MSInspectorSegmentedControl *alignmentButton; // @synthesize alignmentButton=_alignmentButton;
@property(retain, nonatomic) MSInlineUpDownTextField *paragraphHeightField; // @synthesize paragraphHeightField=_paragraphHeightField;
@property(retain, nonatomic) MSInlineUpDownTextField *lineHeightField; // @synthesize lineHeightField=_lineHeightField;
@property(retain, nonatomic) MSInlineUpDownTextField *kerningField; // @synthesize kerningField=_kerningField;
@property(retain, nonatomic) MSStylePartPreviewButton *colorPickerButton; // @synthesize colorPickerButton=_colorPickerButton;
@property(retain, nonatomic) MSInlineUpDownTextFieldWithMenu *fontSizeField; // @synthesize fontSizeField=_fontSizeField;
@property(retain, nonatomic) NSPopUpButton *fontWeightPopUpButton; // @synthesize fontWeightPopUpButton=_fontWeightPopUpButton;
@property(retain, nonatomic) NSButton *fontFamilyButton; // @synthesize fontFamilyButton=_fontFamilyButton;
@property(retain, nonatomic) NSView *basicView; // @synthesize basicView=_basicView;
@property(retain, nonatomic) MSTextInspectorItemDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)inspectorValueAdaptor:(id)arg1 didEncounterError:(id)arg2;
- (id)previewColorSpaceForClient:(id)arg1;
- (void)updateColorButton;
- (void)applyTextColor:(id)arg1;
- (id)inspectorValueAdaptor:(id)arg1 nilOperandDropInForModel:(id)arg2 operator:(id)arg3 operand2:(double)arg4;
- (void)inspectorValueAdaptor:(id)arg1 changeValueUsingBlock:(CDUnknownBlockType)arg2;
- (void)maintainTextLayerBaselinesInBlock:(CDUnknownBlockType)arg1;
- (void)editTextPropertiesInBlock:(CDUnknownBlockType)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)colorInspectorUndoManager:(id)arg1;
- (void)dismissViewController:(id)arg1;
- (void)reloadFontWeightPopUp;
- (void)reloadFontWeightPopUpIfNecessary;
- (id)firstColor;
- (void)changeFontFamilyTo:(id)arg1;
- (id)textEventHandler;
- (id)textView;
- (void)verticalAlignmentAction:(id)arg1;
- (void)textBehaviourButtonAction:(id)arg1;
- (id)contentDrawView;
- (void)putFocusOnTextView;
- (id)companionPopoverForColorPanelPresenter:(id)arg1;
- (void)colorPanelPresenter:(id)arg1 didChangeColor:(id)arg2;
- (void)colorInspectorWillClose:(id)arg1;
- (void)colorInspector:(id)arg1 didChangeToColor:(id)arg2;
- (id)documentColorSpace;
- (id)canvasColorSpace;
- (void)changeTextLayerFont:(id)arg1;
- (void)showColorPickerAction:(id)arg1;
- (void)togglePopover;
- (void)showNativeColorPanel;
- (void)fontSizeMenuAction:(id)arg1;
- (void)fontWeightAction:(id)arg1;
- (void)fontFamilyAction:(id)arg1;
- (void)commitHistory;
- (void)closeExistingPopoverOrShowNewOneWithContentClass:(Class)arg1 sender:(id)arg2 viewCreatorBlock:(CDUnknownBlockType)arg3;
- (void)viewWillDisappear;
- (void)dealloc;
- (double)defaultLineHeight;
- (void)reloadVerticalAlignmentButton;
- (void)updateDisplayedValues;
- (void)textViewDidChange:(id)arg1;
- (void)viewDidLoad;
- (id)fontSizeMenu;
- (void)writeRun:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <MSTextLayerItemDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

