//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSTile;

@protocol MSTileDelegate <NSObject>
- (void)tile:(MSTile *)arg1 renderOverlayInRect:(struct CGRect)arg2;
@end

