//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class CALayer, MSImmutableDocumentData, MSImmutablePage, MSTileRenderer, NSArray;

@interface MSTileRenderOperation : NSOperation
{
    BOOL _shouldDrawPixelated;
    BOOL _drawDottedDirtyRect;
    id <MSTileRenderOperationDelegate> _delegate;
    CALayer *_contentLayer;
    CALayer *_backgroundLayer;
    struct CGContext *_contentCGContext;
    struct CGImage *_image;
    double _zoomValue;
    MSImmutablePage *_pageForContent;
    MSImmutableDocumentData *_document;
    NSArray *_artboardFrames;
    id <MSRenderingContextCacheProvider> _renderingCacheProvider;
    MSTileRenderer *_tileRenderer;
    struct CGPoint _distanceFromScrollOrigin;
    struct CGRect _contentRectNeedingRedraw;
}

@property(retain, nonatomic) MSTileRenderer *tileRenderer; // @synthesize tileRenderer=_tileRenderer;
@property(retain, nonatomic) id <MSRenderingContextCacheProvider> renderingCacheProvider; // @synthesize renderingCacheProvider=_renderingCacheProvider;
@property(retain, nonatomic) NSArray *artboardFrames; // @synthesize artboardFrames=_artboardFrames;
@property(retain, nonatomic) MSImmutableDocumentData *document; // @synthesize document=_document;
@property(retain, nonatomic) MSImmutablePage *pageForContent; // @synthesize pageForContent=_pageForContent;
@property(nonatomic) double zoomValue; // @synthesize zoomValue=_zoomValue;
@property(nonatomic) struct CGPoint distanceFromScrollOrigin; // @synthesize distanceFromScrollOrigin=_distanceFromScrollOrigin;
@property(nonatomic) BOOL drawDottedDirtyRect; // @synthesize drawDottedDirtyRect=_drawDottedDirtyRect;
@property(nonatomic) BOOL shouldDrawPixelated; // @synthesize shouldDrawPixelated=_shouldDrawPixelated;
@property(nonatomic) struct CGRect contentRectNeedingRedraw; // @synthesize contentRectNeedingRedraw=_contentRectNeedingRedraw;
@property(readonly, nonatomic) struct CGImage *image; // @synthesize image=_image;
@property(nonatomic) struct CGContext *contentCGContext; // @synthesize contentCGContext=_contentCGContext;
@property(retain, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(retain, nonatomic) CALayer *contentLayer; // @synthesize contentLayer=_contentLayer;
@property(nonatomic) __weak id <MSTileRenderOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)drawArtboardBackgroundsInContext:(struct CGContext *)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)drawContentInContext:(struct CGContext *)arg1;
- (struct CGPoint)scrollOriginAdjustedForPixelZoom;
- (void)drawPage:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)main;
- (void)cancelDrawing;
- (void)dealloc;

@end

