//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSToolController : NSObject
{
    unsigned long long _state;
}

@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void)reset;

@end

