//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface MSTooltipHostingView : NSView
{
    NSView *_toolTipProvider;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSView *toolTipProvider; // @synthesize toolTipProvider=_toolTipProvider;
- (void)refreshToolTip;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)setupTooltipHostingView;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

