//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSString, NSTextField;

@interface MSUnavailableUpdatesWindowController : NSWindowController <NSWindowDelegate>
{
    NSTextField *_descriptionTextField;
    NSString *_lastVersion;
    NSString *_lastBuildNumber;
}

+ (void)showModalWithVersion:(id)arg1 buildNumber:(id)arg2;
@property(retain, nonatomic) NSString *lastBuildNumber; // @synthesize lastBuildNumber=_lastBuildNumber;
@property(retain, nonatomic) NSString *lastVersion; // @synthesize lastVersion=_lastVersion;
@property(nonatomic) __weak NSTextField *descriptionTextField; // @synthesize descriptionTextField=_descriptionTextField;
- (void).cxx_destruct;
- (void)learnMore:(id)arg1;
- (void)openUpdatesPage:(id)arg1;
- (void)renewLicense:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (id)initWithWindowNibName:(id)arg1 version:(id)arg2 buildNumber:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

