//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SUUpdaterDelegate.h"

@class NSString;

@interface MSUpdateController : NSObject <SUUpdaterDelegate>
{
    BOOL _hasAvailableUpdates;
    BOOL _updateInProgress;
    unsigned long long _unavailableUpdateCount;
}

@property(nonatomic) BOOL updateInProgress; // @synthesize updateInProgress=_updateInProgress;
@property(nonatomic) BOOL hasAvailableUpdates; // @synthesize hasAvailableUpdates=_hasAvailableUpdates;
@property(nonatomic) unsigned long long unavailableUpdateCount; // @synthesize unavailableUpdateCount=_unavailableUpdateCount;
- (id)bestValidUpdateInAppcast:(id)arg1 forUpdater:(id)arg2;
- (id)checkerWithAppcast:(id)arg1;
- (void)parseAppcast:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)storeResultsFromChecker:(id)arg1;
- (id)feedURLStringForUpdater:(id)arg1;
- (void)appCastFetchFailedWithError:(id)arg1;
- (void)fetchAppcastWithCompletion:(CDUnknownBlockType)arg1;
- (id)commandLabel;
- (BOOL)commandEnabled;
- (void)checkNormally;
- (void)checkSilently;
- (void)checkQuietly;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

