//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSPopoverAction.h"

@class NSString, NSViewController;

@interface MSWorkspaceUnavailableAction : MSPopoverAction
{
}

- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithDocument:(id)arg1;
- (void)learnMoreAboutLicense:(id)arg1;
@property(nonatomic, readonly) NSViewController *popoverViewController;
@property(nonatomic, readonly) NSString *imageName;
@property(nonatomic, readonly) BOOL hasSubMenu;
@property(nonatomic, readonly) NSString *tooltip;
@property(nonatomic, readonly) NSString *label;

@end

