//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (BCFoundation)
+ (id)arrayByMergingArrays:(id)arg1;
+ (id)arrayWithCapacity:(unsigned long long)arg1 fill:(CDUnknownBlockType)arg2;
+ (id)flattenedArrays:(id)arg1;
- (id)loopingEnumerator;
- (unsigned long long)indexOfSubArray:(id)arg1;
- (id)rotateTwoDimensionalArray;
- (id)uniqueObjects;
- (id)subArrayToIndex:(unsigned long long)arg1;
- (id)objectAtIndexOrNil:(unsigned long long)arg1;
- (BOOL)isValidIndex:(unsigned long long)arg1;
- (id)dictionaryByIndexingObjectForKey:(id)arg1;
- (id)arrayByAddingObjects:(id)arg1;
- (id)arrayByRemovingObjects:(id)arg1;
- (id)arrayByRemovingObject:(id)arg1;
- (id)shuffledArray;
- (id)sortedArrayUsingKey:(id)arg1 selector:(SEL)arg2;
- (id)sortedArrayUsingKey:(id)arg1;
- (id)sortedArray;
- (id)arrayByRemovingNull;
- (BOOL)containsOnlyObjectsOfClass:(Class)arg1;
- (id)mutableCopyDeep;
- (id)copyDeep;
- (double)sum:(CDUnknownBlockType)arg1;
- (id)firstObjectOfClass:(Class)arg1;
- (BOOL)containsObjectOfClass:(Class)arg1;
- (id)reversedArray;
- (void)enumerateTailUsingBlock:(CDUnknownBlockType)arg1;
- (id)arrayByRemovingLastObject;
- (id)tail;
- (unsigned long long)indexOfFirstObjectPassingTest:(CDUnknownBlockType)arg1;
- (id)firstObjectPassingTest:(CDUnknownBlockType)arg1;
- (BOOL)containsObjectPassingTest:(CDUnknownBlockType)arg1;
- (id)filteredByObjectsOfClass:(Class)arg1;
- (id)filterWithIndex:(CDUnknownBlockType)arg1;
- (id)filter:(CDUnknownBlockType)arg1;
- (void)enumerateWithIndex:(CDUnknownBlockType)arg1;
- (void)enumerate:(CDUnknownBlockType)arg1;
- (id)mapWithIndex:(CDUnknownBlockType)arg1;
- (id)compactMap:(CDUnknownBlockType)arg1;
- (id)map:(CDUnknownBlockType)arg1;
- (id)front;
- (id)editSequenceTo:(id)arg1 inferringMoves:(BOOL)arg2;
- (id)editSequenceTo:(id)arg1 inferringMoves:(BOOL)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void)finishEncodingObject:(id)arg1;
- (void)startEncodingObject:(id)arg1;
- (void)encodeAsJSON:(id)arg1;
- (unsigned long long)applyBlockConcurrentlyAndCountSuccess:(CDUnknownBlockType)arg1;
- (void)mapWithMaxConcurrencyCount:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
@end

