//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (ModelSyncSupport)
- (BOOL)propertiesAreEqual:(id)arg1;
- (BOOL)fuzzyIsEqualFloatValueForKey:(id)arg1 otherDictionary:(id)arg2 precision:(double)arg3;
@end

