//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (LayerListPreviewIconBadging)
- (id)badgedWithImage:(id)arg1 maskImage:(id)arg2 offset:(struct CGPoint)arg3 forImageOwner:(id)arg4;
- (id)badgedWithImageNamed:(id)arg1 maskImageNamed:(id)arg2 offset:(struct CGPoint)arg3 forImageOwner:(id)arg4;
- (id)badgedAs:(unsigned long long)arg1 forImageOwner:(id)arg2;
@end

