//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSSet.h>

@interface NSSet (BCFoundation)
- (id)compactMap:(CDUnknownBlockType)arg1;
- (id)setMinusSet:(id)arg1;
- (id)sortedArrayUsingKey:(id)arg1;
- (BOOL)isEquivalentToArray_bc:(id)arg1;
@end

