//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (SHA1)
+ (id)stringWithPrefix:(id)arg1 number:(long long)arg2;
@property(readonly, nonatomic) NSString *sha1String_bc;
- (id)sha1;
- (id)safeSubstringWithRange_ms:(struct _NSRange)arg1;
- (id)safeSubstringFromIndex_ms:(unsigned long long)arg1;
- (id)safeSubstringToIndex_ms:(unsigned long long)arg1;
- (id)words;
- (BOOL)isValidEmailAddress;
- (BOOL)hasExtension:(id)arg1;
- (id)expandTilde;
- (id)withExtension:(id)arg1;
- (id)withoutExtension;
- (id)extension;
- (id)child:(id)arg1;
- (id)parent;
- (id)uniqueStringComparedToStrings:(id)arg1 includeCopySuffix:(BOOL)arg2;
- (id)splitByBaseAndNumber;
- (BOOL)containsCharacter:(unsigned short)arg1;
- (BOOL)containsSubstring:(id)arg1;
- (id)trimmedString;
- (id)stringWithFirstCharacterLowercase;
- (BOOL)hasSuffix_bc:(id)arg1 options:(unsigned long long)arg2;
- (id)stringByAppendingPathComponents:(id)arg1;
- (id)stringByStrippingStrings:(id)arg1;
- (id)stringByDeletingSuffix:(id)arg1;
- (id)stringByDeletingPrefix:(id)arg1;
- (void)encodeAsKey:(id)arg1;
- (void)encodeAsRAWArchive:(id)arg1;
- (id)safeJSONValue;
@end

