//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <BCFoundation/BCURLOperation.h>

@class NSError, NSObject, NSURLSessionDataTask, _TtC14SketchCloudKit29SCKAPIOperationProgressHelper;
@protocol OS_dispatch_group, SCKAPIOperationDelegate, SCKAPIRequest;

@interface SCKAPIOperation : BCURLOperation
{
    id <SCKAPIOperationDelegate> _delegate;
    CDUnknownBlockType _requestCompletionBlock;
    id <SCKAPIRequest> _request;
    NSError *_error;
    NSURLSessionDataTask *_task;
    NSObject<OS_dispatch_group> *_authRefreshGroup;
    _TtC14SketchCloudKit29SCKAPIOperationProgressHelper *_progressHelper;
}

+ (id)clientToken;
+ (void)setClientID:(id)arg1;
+ (id)clientID;
+ (void)setApplicationBundle:(id)arg1;
+ (id)applicationBundle;
+ (id)additionalHeaders;
+ (id)defaultURLSession;
+ (id)requestAllProjectsWithHandler:(CDUnknownBlockType)arg1;
+ (id)renameShare:(id)arg1 newName:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)updateShare:(id)arg1 libraryEnabled:(BOOL)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)moveShareOperation:(id)arg1 toProject:(id)arg2 environment:(id)arg3 authentication:(id)arg4 handler:(CDUnknownBlockType)arg5;
+ (id)requestShareAtURL:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)requestShareWithShortID:(id)arg1 environment:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)requestUpdatedShare:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)requestShareWithObjectID:(id)arg1 environment:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) _TtC14SketchCloudKit29SCKAPIOperationProgressHelper *progressHelper; // @synthesize progressHelper=_progressHelper;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *authRefreshGroup; // @synthesize authRefreshGroup=_authRefreshGroup;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(retain) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) id <SCKAPIRequest> request; // @synthesize request=_request;
@property(copy, nonatomic) CDUnknownBlockType requestCompletionBlock; // @synthesize requestCompletionBlock=_requestCompletionBlock;
@property(nonatomic) __weak id <SCKAPIOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void)processData:(id)arg1 response:(id)arg2 error:(id)arg3;
- (void)cancel;
- (void)applicationWillTerminate:(id)arg1;
- (void)refreshAuthentication;
- (void)performRequest;
- (void)start;
- (id)initWithRequest:(id)arg1;
- (id)init;

@end

