//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchCloudKit/NSObject-Protocol.h>
#import <SketchCloudKit/SCKSensitiveMetadata-Protocol.h>

@class NSString, SCKAvatar, SCKPaginatedProjects, SCKPaginatedShares;

@protocol SCKContentOwner <NSObject, SCKSensitiveMetadata>
@property(nonatomic, readonly) SCKPaginatedProjects *paginatedProjects;
@property(nonatomic, readonly) SCKPaginatedShares *paginatedShares;
@property(nonatomic, readonly) SCKAvatar *avatar;
@property(nonatomic, readonly) NSString *name;
@end

