//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchCloudKit/SCKAPIOperation.h>

@class SCKAPISession;

@interface SCKOAuthAPIOperation : SCKAPIOperation
{
    SCKAPISession *_authentication;
}

+ (void)refreshLicenseWithAuthentication:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)refreshAuthentication:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)refreshSession:(id)arg1 withRequest:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)signinWithEmail:(id)arg1 password:(id)arg2 handler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) SCKAPISession *authentication; // @synthesize authentication=_authentication;
- (void).cxx_destruct;
- (void)processData:(id)arg1 response:(id)arg2 error:(id)arg3;
- (void)refreshAuthentication;
- (id)initWithRequest:(id)arg1;

@end

