//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchCloudKit/SCKAPIOperation.h>

@class NSArray, SCKAPIURLRequest;

@interface SCKRestAPIOperation : SCKAPIOperation
{
    NSArray *_result;
}

+ (void)executeRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)resultOfType:(Class)arg1 fromData:(id)arg2 error:(id *)arg3;
- (void).cxx_destruct;
@property(readonly) NSArray *result; // @synthesize result=_result;
- (id)resultFromData:(id)arg1 error:(id *)arg2;
- (void)processData:(id)arg1 response:(id)arg2 error:(id)arg3;

// Remaining properties
@property(retain, nonatomic) SCKAPIURLRequest *request; // @dynamic request;

@end

