//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchCloudKit/SCKEvent.h>

@interface SCKShareChangedEvent : SCKEvent
{
    // Error parsing type: , name: share
    // Error parsing type: , name: type
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithDictionary:(id)arg1;

@end

