//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCKUser;

@interface SCKUserController : NSObject
{
    // Error parsing type: , name: user
    // Error parsing type: , name: isLoading
    // Error parsing type: , name: requestOperation
    // Error parsing type: , name: requestHandlers
}

+ (id)userDidChangeNotification;
- (void).cxx_destruct;
- (void)currentEnvironmentDidChangeWithNotification:(id)arg1;
- (void)currentAuthenticationSessionDidChangeWithNotification:(id)arg1;
- (void)requestUserWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)init;
@property(nonatomic) BOOL isLoading; // @synthesize isLoading;
@property(nonatomic, retain) SCKUser *user; // @synthesize user;

@end

