//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSImmutableDocumentData, MSImmutableSymbolInstance, MSSVGFilter, NSAffineTransform, NSMutableArray, NSMutableDictionary, NSSet, NSString, NSXMLDocument, NSXMLElement;

@interface SketchSVGExporter : NSObject
{
    NSString *_mask;
    NSString *_currentShapeDef;
    unsigned long long _exporterOptions;
    MSImmutableDocumentData *_document;
    MSSVGFilter *_currentFilterGroup;
    MSImmutableSymbolInstance *_currentSymbolInstance;
    NSXMLDocument *_doc;
    NSXMLElement *_defs;
    NSXMLElement *_root;
    NSAffineTransform *_initialMove;
    NSMutableDictionary *_gradients;
    unsigned long long _nextUniqueID;
    NSMutableArray *_parentStack;
    NSSet *_includedLayerIDs;
    struct CGRect _exportBounds;
}

@property(readonly, nonatomic) NSSet *includedLayerIDs; // @synthesize includedLayerIDs=_includedLayerIDs;
@property(readonly, nonatomic) NSMutableArray *parentStack; // @synthesize parentStack=_parentStack;
@property(nonatomic) unsigned long long nextUniqueID; // @synthesize nextUniqueID=_nextUniqueID;
@property(readonly, nonatomic) NSMutableDictionary *gradients; // @synthesize gradients=_gradients;
@property(readonly, nonatomic) NSAffineTransform *initialMove; // @synthesize initialMove=_initialMove;
@property(readonly, nonatomic) NSXMLElement *root; // @synthesize root=_root;
@property(readonly, nonatomic) NSXMLElement *defs; // @synthesize defs=_defs;
@property(readonly, nonatomic) NSXMLDocument *doc; // @synthesize doc=_doc;
@property(retain, nonatomic) MSImmutableSymbolInstance *currentSymbolInstance; // @synthesize currentSymbolInstance=_currentSymbolInstance;
@property(retain, nonatomic) MSSVGFilter *currentFilterGroup; // @synthesize currentFilterGroup=_currentFilterGroup;
@property(retain, nonatomic) MSImmutableDocumentData *document; // @synthesize document=_document;
@property(readonly, nonatomic) unsigned long long exporterOptions; // @synthesize exporterOptions=_exporterOptions;
@property(retain, nonatomic) NSString *currentShapeDef; // @synthesize currentShapeDef=_currentShapeDef;
@property(retain, nonatomic) NSString *mask; // @synthesize mask=_mask;
@property(readonly, nonatomic) struct CGRect exportBounds; // @synthesize exportBounds=_exportBounds;
- (void).cxx_destruct;
- (BOOL)layerIsIncluded:(id)arg1;
- (BOOL)isDrawingSymbolInstance;
- (void)drawSymbolInstance:(id)arg1 inBlock:(CDUnknownBlockType)arg2;
- (void)performWithParent:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)popParent;
- (void)pushParent:(id)arg1;
- (id)parentForLayer:(id)arg1;
- (id)ancestorsForLayer:(id)arg1;
- (id)radialGradientAttributes:(id)arg1;
- (id)linearGradientAttributes:(id)arg1;
- (id)stopsForGradient:(id)arg1;
- (id)gradientElement:(id)arg1;
- (void)addGradient:(id)arg1;
- (id)hashForGradient:(id)arg1;
- (BOOL)endFilterGroup;
- (id)beginFilterGroup;
- (id)addDefinitionWithWithName:(id)arg1 children:(id)arg2 attributes:(id)arg3;
- (id)uniqueIDForElementWithName:(id)arg1;
- (void)setDescription:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)normalizePath:(id)arg1;
- (struct CGPoint)normalizePoint:(struct CGPoint)arg1;
- (id)description;
- (id)exportLayers:(id)arg1;
- (id)initWithName:(id)arg1 exportRequest:(id)arg2 options:(unsigned long long)arg3;
- (id)init;
- (void)setupCommonElements:(id)arg1;

@end

