//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SketchMirrorTalk/SMKConnection.h>

#import <SketchMirrorServerKit/NSNetServiceDelegate-Protocol.h>
#import <SketchMirrorServerKit/PSWebSocketDelegate-Protocol.h>

@class NSDictionary, NSError, NSNetService, NSString, PSWebSocket;

@interface SMKWebServerConnection : SMKConnection <PSWebSocketDelegate, NSNetServiceDelegate>
{
    NSDictionary *_advertisement;
    NSError *_error;
    NSNetService *_netService;
    PSWebSocket *_webSocket;
}

+ (unsigned long long)port;
- (void).cxx_destruct;
@property(retain, nonatomic) PSWebSocket *webSocket; // @synthesize webSocket=_webSocket;
@property(retain, nonatomic) NSNetService *netService; // @synthesize netService=_netService;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSDictionary *advertisement; // @synthesize advertisement=_advertisement;
- (void)webSocket:(id)arg1 didCloseWithCode:(long long)arg2 reason:(id)arg3 wasClean:(BOOL)arg4;
- (void)webSocket:(id)arg1 didReceiveMessage:(id)arg2;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;
- (void)netServiceDidStop:(id)arg1;
- (void)netService:(id)arg1 didUpdateTXTRecordData:(id)arg2;
- (void)netServiceDidResolveAddress:(id)arg1;
- (void)netService:(id)arg1 didNotResolve:(id)arg2;
- (void)startPinging;
- (void)sendData:(id)arg1;
- (void)close;
- (void)connect;
- (void)updateAdvertisement;
- (unsigned long long)connectionType;
- (void)dealloc;
- (id)initWithWebSocket:(id)arg1;
- (id)initWithNetService:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

